{"website": 3, "end": "2015-10-17", "author": "Shirin Tinati", "type": 1, "pledged": "13355", "title": "\"I Am Warrior\" a Photo Book to Empower Women During Breast Cancer Treatment", "project_url": "https://www.rockethub.com/projects/60987-i-am-warrior-a-photo-book-to-empower-women-during-breast-cancer-treatment", "currency": "USD", "location": "no location", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60987/1444154811-large.png", "id": "60987"}
{"website": 3, "end": "2015-10-31", "author": "Brad L. Baird", "type": 1, "pledged": "35", "title": "\"Fred's Story\" - Family Hospitals & Senior Centres Book Placement Program", "project_url": "https://www.rockethub.com/projects/61531-fred-s-story-family-hospitals-senior-centres-book-placement-program", "currency": "USD", "location": "Edmonton, Canada", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61531/1442486052-large.jpg", "id": "61531"}
{"website": 3, "end": "2015-10-17", "author": "Shirin Tinati", "type": 1, "pledged": "13355", "title": "\"I Am Warrior\" a Photo Book to Empower Women During Breast Cancer Treatment", "project_url": "https://www.rockethub.com/projects/60987-i-am-warrior-a-photo-book-to-empower-women-during-breast-cancer-treatment", "currency": "USD", "location": "no location", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60987/1444154811-large.png", "id": "60987"}
{"website": 3, "end": "2015-12-09", "author": "Wayde Fishman", "type": 1, "pledged": "3070", "title": "PRICE FOR PARADISE -The Struggles & Successes of living the Real Hawaii", "project_url": "https://www.rockethub.com/projects/58805-price-for-paradise-the-struggles-successes-of-living-the-real-hawaii", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58805/1435718773-large.jpg", "id": "58805"}
{"website": 3, "end": "2015-10-26", "author": "Pablo Gracia", "type": 1, "pledged": "0", "title": "help the future of cinematography , film making and music production", "project_url": "https://www.rockethub.com/projects/59905-help-the-future-of-cinematography-film-making-and-music-production", "currency": "USD", "location": "no location", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59905/1438104815-large.jpg", "id": "59905"}
{"website": 3, "end": "2015-12-04", "author": "Von-Anise McCoy", "type": 1, "pledged": "350", "title": "Bougie Betty", "project_url": "https://www.rockethub.com/projects/60732-bougie-betty", "currency": "USD", "location": "New York , NY", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60732/1443728809-large.JPG", "id": "60732"}
{"website": 3, "end": "2015-12-04", "author": "Von-Anise McCoy", "type": 1, "pledged": "350", "title": "Bougie Betty", "project_url": "https://www.rockethub.com/projects/60732-bougie-betty", "currency": "USD", "location": "New York , NY", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60732/1443728809-large.JPG", "id": "60732"}
{"website": 3, "end": "2015-10-17", "author": "Shirin Tinati", "type": 1, "pledged": "13355", "title": "\"I Am Warrior\" a Photo Book to Empower Women During Breast Cancer Treatment", "project_url": "https://www.rockethub.com/projects/60987-i-am-warrior-a-photo-book-to-empower-women-during-breast-cancer-treatment", "currency": "USD", "location": "no location", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60987/1444154811-large.png", "id": "60987"}
{"website": 3, "end": "2015-11-08", "author": "Scott Ambrose", "type": 1, "pledged": "130", "title": "The Sincerity Lodge Charity Christmas Tree for Kennedy Krieger Festival", "project_url": "https://www.rockethub.com/projects/61989-the-sincerity-lodge-charity-christmas-tree-for-kennedy-krieger-festival", "currency": "USD", "location": "Baltimore, MD", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61989/1444443463-large.jpg", "id": "61989"}
{"website": 3, "end": "2015-10-20", "author": "Shako Khiski", "type": 1, "pledged": "3885", "title": "Help Shako Raise $3000 in 30 Days For His EP!", "project_url": "https://www.rockethub.com/projects/60660-help-shako-raise-3000-in-30-days-for-his-ep", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60660/1442533702-large.jpg", "id": "60660"}
{"website": 3, "end": "2015-11-09", "author": "Wyrd Theatre", "type": 1, "pledged": "1405", "title": "Support Wyrd Theatre's \"Tartuffe en Burlesque!\"", "project_url": "https://www.rockethub.com/projects/61413-support-wyrd-theatre-s-tartuffe-en-burlesque", "currency": "USD", "location": "no location", "category_id": "3", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61413/1444276531-large.jpg", "id": "61413"}
{"website": 3, "end": "2015-10-23", "author": "Eleonore Nitzschke", "type": 1, "pledged": "5", "title": "The spiral of adventure", "project_url": "https://www.rockethub.com/projects/59779-the-spiral-of-adventure", "currency": "USD", "location": "New York City , NY", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59779/1437681001-large.JPG", "id": "59779"}
{"website": 3, "end": "2015-11-20", "author": "Steve Thornton", "type": 1, "pledged": "200", "title": "Help Stephen attend AND's November Per4mance Intensive Workshop", "project_url": "https://www.rockethub.com/projects/61621-help-stephen-attend-and-s-november-per4mance-intensive-workshop", "currency": "USD", "location": "Brooklyn, NY", "category_id": "12", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61621/1442776516-large.jpg", "id": "61621"}
{"website": 3, "end": "2015-12-31", "author": "Nasya Kamrat", "type": 1, "pledged": "6616", "title": "UNSPEAKABLE: An Animated Holocaust Documentary", "project_url": "https://www.rockethub.com/projects/43758-unspeakable-an-animated-holocaust-documentary", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/43758/1401759333-large.jpg", "id": "43758"}
{"website": 3, "end": "2015-10-20", "author": "Shako Khiski", "type": 1, "pledged": "3885", "title": "Help Shako Raise $3000 in 30 Days For His EP!", "project_url": "https://www.rockethub.com/projects/60660-help-shako-raise-3000-in-30-days-for-his-ep", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60660/1442533702-large.jpg", "id": "60660"}
{"website": 3, "end": "2015-10-18", "author": "Jack Resweber", "type": 1, "pledged": "1582", "title": "Support the Development of Phonec for Mac and Windows 64-bit", "project_url": "https://www.rockethub.com/projects/61286-support-the-development-of-phonec-for-mac-and-windows-64-bit", "currency": "USD", "location": "New Orleans, LA", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61286/1442335905-large.jpg", "id": "61286"}
{"website": 3, "end": "2015-10-31", "author": "Joe Cristina", "type": 1, "pledged": "315", "title": "KidWorks Avanti Music Program", "project_url": "https://www.rockethub.com/projects/59922-kidworks-avanti-music-program", "currency": "USD", "location": "no location", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59922/1439076763-large.png", "id": "59922"}
{"website": 3, "end": "2015-10-31", "author": "Joe Cristina", "type": 1, "pledged": "315", "title": "KidWorks Avanti Music Program", "project_url": "https://www.rockethub.com/projects/59922-kidworks-avanti-music-program", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59922/1439076763-large.png", "id": "59922"}
{"website": 3, "end": "2015-11-06", "author": "Fred Sauter", "type": 1, "pledged": "5370", "title": "Fund Astronaut Love Show -a new musical by Leschen & Sauter (Bedbugs!!!)", "project_url": "https://www.rockethub.com/projects/61801-fund-astronaut-love-show-a-new-musical-by-leschen-sauter-bedbugs", "currency": "USD", "location": "no location", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61801/1444588774-large.gif", "id": "61801"}
{"website": 3, "end": "2015-11-06", "author": "Fred Sauter", "type": 1, "pledged": "5370", "title": "Fund Astronaut Love Show -a new musical by Leschen & Sauter (Bedbugs!!!)", "project_url": "https://www.rockethub.com/projects/61801-fund-astronaut-love-show-a-new-musical-by-leschen-sauter-bedbugs", "currency": "USD", "location": "no location", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61801/1444588774-large.gif", "id": "61801"}
{"website": 3, "end": "2015-11-06", "author": "Fred Sauter", "type": 1, "pledged": "5370", "title": "Fund Astronaut Love Show -a new musical by Leschen & Sauter (Bedbugs!!!)", "project_url": "https://www.rockethub.com/projects/61801-fund-astronaut-love-show-a-new-musical-by-leschen-sauter-bedbugs", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61801/1444588774-large.gif", "id": "61801"}
{"website": 3, "end": "2015-11-06", "author": "Fred Sauter", "type": 1, "pledged": "5370", "title": "Fund Astronaut Love Show -a new musical by Leschen & Sauter (Bedbugs!!!)", "project_url": "https://www.rockethub.com/projects/61801-fund-astronaut-love-show-a-new-musical-by-leschen-sauter-bedbugs", "currency": "USD", "location": "no location", "category_id": "3", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61801/1444588774-large.gif", "id": "61801"}
{"website": 3, "end": "2015-11-06", "author": "Fred Sauter", "type": 1, "pledged": "5370", "title": "Fund Astronaut Love Show -a new musical by Leschen & Sauter (Bedbugs!!!)", "project_url": "https://www.rockethub.com/projects/61801-fund-astronaut-love-show-a-new-musical-by-leschen-sauter-bedbugs", "currency": "USD", "location": "no location", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61801/1444588774-large.gif", "id": "61801"}
{"website": 3, "end": "2015-11-06", "author": "Fred Sauter", "type": 1, "pledged": "5370", "title": "Fund Astronaut Love Show -a new musical by Leschen & Sauter (Bedbugs!!!)", "project_url": "https://www.rockethub.com/projects/61801-fund-astronaut-love-show-a-new-musical-by-leschen-sauter-bedbugs", "currency": "USD", "location": "no location", "category_id": "12", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61801/1444588774-large.gif", "id": "61801"}
{"website": 3, "end": "2015-11-06", "author": "Fred Sauter", "type": 1, "pledged": "5370", "title": "Fund Astronaut Love Show -a new musical by Leschen & Sauter (Bedbugs!!!)", "project_url": "https://www.rockethub.com/projects/61801-fund-astronaut-love-show-a-new-musical-by-leschen-sauter-bedbugs", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61801/1444588774-large.gif", "id": "61801"}
{"website": 3, "end": "2015-11-06", "author": "Fred Sauter", "type": 1, "pledged": "5370", "title": "Fund Astronaut Love Show -a new musical by Leschen & Sauter (Bedbugs!!!)", "project_url": "https://www.rockethub.com/projects/61801-fund-astronaut-love-show-a-new-musical-by-leschen-sauter-bedbugs", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61801/1444588774-large.gif", "id": "61801"}
{"website": 3, "end": "2015-11-30", "author": "Rupert Marshall-Luck", "type": 1, "pledged": "2695", "title": "Premi\u00e8re recording of British Romantic masterpieces", "project_url": "https://www.rockethub.com/projects/60297-premiere-recording-of-british-romantic-masterpieces", "currency": "USD", "location": "no location", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60297/1439226111-large.jpg", "id": "60297"}
{"website": 3, "end": "2015-11-08", "author": "Scott Ambrose", "type": 1, "pledged": "130", "title": "The Sincerity Lodge Charity Christmas Tree for Kennedy Krieger Festival", "project_url": "https://www.rockethub.com/projects/61989-the-sincerity-lodge-charity-christmas-tree-for-kennedy-krieger-festival", "currency": "USD", "location": "Baltimore, MD", "category_id": "4", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61989/1444443463-large.jpg", "id": "61989"}
{"website": 3, "end": "2016-01-17", "author": "Penn State Lunar Lion Team", "type": 1, "pledged": "172452", "title": "Lunar Lion - the first ever university-led mission to the Moon", "project_url": "https://www.rockethub.com/projects/34210-lunar-lion-the-first-ever-university-led-mission-to-the-moon", "currency": "USD", "location": "University Park, PA", "category_id": "14", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/34210/1389827818-large.jpg", "id": "34210"}
{"website": 3, "end": "2015-11-15", "author": "Karina Mirochnik", "type": 1, "pledged": "1410", "title": "Women Across Frontiers & MADRE - International Fundraising Initiative", "project_url": "https://www.rockethub.com/projects/59706-women-across-frontiers-madre-international-fundraising-initiative", "currency": "USD", "location": "no location", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59706/1437501826-large.jpg", "id": "59706"}
{"website": 3, "end": "2015-11-09", "author": "Laurie Carrigan", "type": 1, "pledged": "625", "title": "ACPW's Women in Transition Career Conference", "project_url": "https://www.rockethub.com/projects/61810-acpw-s-women-in-transition-career-conference", "currency": "USD", "location": "Quantico, Stafford, Va", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61810/1443163241-large.jpg", "id": "61810"}
{"website": 3, "end": "2015-11-01", "author": "Sugar Free The Movie", "type": 1, "pledged": "1201", "title": "Sugar Free The Movie- Break The Addiction", "project_url": "https://www.rockethub.com/projects/57823-sugar-free-the-movie-break-the-addiction", "currency": "USD", "location": "no location", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/57823/1436497057-large.jpg", "id": "57823"}
{"website": 3, "end": "2016-01-17", "author": "Penn State Lunar Lion Team", "type": 1, "pledged": "172452", "title": "Lunar Lion - the first ever university-led mission to the Moon", "project_url": "https://www.rockethub.com/projects/34210-lunar-lion-the-first-ever-university-led-mission-to-the-moon", "currency": "USD", "location": "University Park, PA", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/34210/1389827818-large.jpg", "id": "34210"}
{"website": 3, "end": "2015-10-31", "author": "Dennis Nakamura", "type": 1, "pledged": "200", "title": "Cosmo Pen and Cartridges", "project_url": "https://www.rockethub.com/projects/44024-cosmo-pen-and-cartridges", "currency": "USD", "location": "no location", "category_id": "5", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/44024/1401485868-large.jpg", "id": "44024"}
{"website": 3, "end": "2015-10-29", "author": "Tomasz Trzcinski", "type": 1, "pledged": "10", "title": "I would like to help charities", "project_url": "https://www.rockethub.com/projects/60000-i-would-like-to-help-charities", "currency": "USD", "location": "Szczytno, Poland", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60000/1438361076-large.jpg", "id": "60000"}
{"website": 3, "end": "2015-10-17", "author": "Danie Lito", "type": 1, "pledged": "0", "title": "Nomad Tiny House", "project_url": "https://www.rockethub.com/projects/59677-nomad-tiny-house", "currency": "USD", "location": "Bucharest, Romania", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59677/1437398223-large.jpg", "id": "59677"}
{"website": 3, "end": "2015-10-17", "author": "Danie Lito", "type": 1, "pledged": "0", "title": "Nomad Tiny House", "project_url": "https://www.rockethub.com/projects/59677-nomad-tiny-house", "currency": "USD", "location": "Bucharest, Romania", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59677/1437398223-large.jpg", "id": "59677"}
{"website": 3, "end": "2015-11-08", "author": "jay", "type": 1, "pledged": "0", "title": "Start up support for Comited Models Limited", "project_url": "https://www.rockethub.com/projects/60303-start-up-support-for-comited-models-limited", "currency": "USD", "location": "no location", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60303/1439240897-large.jpg", "id": "60303"}
{"website": 3, "end": "2015-11-08", "author": "jay", "type": 1, "pledged": "0", "title": "Start up support for Comited Models Limited", "project_url": "https://www.rockethub.com/projects/60303-start-up-support-for-comited-models-limited", "currency": "USD", "location": "no location", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60303/1439240897-large.jpg", "id": "60303"}
{"website": 3, "end": "2015-11-08", "author": "jay", "type": 1, "pledged": "0", "title": "Start up support for Comited Models Limited", "project_url": "https://www.rockethub.com/projects/60303-start-up-support-for-comited-models-limited", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60303/1439240897-large.jpg", "id": "60303"}
{"website": 3, "end": "2015-11-08", "author": "jay", "type": 1, "pledged": "0", "title": "Start up support for Comited Models Limited", "project_url": "https://www.rockethub.com/projects/60303-start-up-support-for-comited-models-limited", "currency": "USD", "location": "no location", "category_id": "3", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60303/1439240897-large.jpg", "id": "60303"}
{"website": 3, "end": "2015-11-08", "author": "jay", "type": 1, "pledged": "0", "title": "Start up support for Comited Models Limited", "project_url": "https://www.rockethub.com/projects/60303-start-up-support-for-comited-models-limited", "currency": "USD", "location": "no location", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60303/1439240897-large.jpg", "id": "60303"}
{"website": 3, "end": "2015-11-08", "author": "jay", "type": 1, "pledged": "0", "title": "Start up support for Comited Models Limited", "project_url": "https://www.rockethub.com/projects/60303-start-up-support-for-comited-models-limited", "currency": "USD", "location": "no location", "category_id": "12", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60303/1439240897-large.jpg", "id": "60303"}
{"website": 3, "end": "2015-11-08", "author": "jay", "type": 1, "pledged": "0", "title": "Start up support for Comited Models Limited", "project_url": "https://www.rockethub.com/projects/60303-start-up-support-for-comited-models-limited", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60303/1439240897-large.jpg", "id": "60303"}
{"website": 3, "end": "2015-11-08", "author": "jay", "type": 1, "pledged": "0", "title": "Start up support for Comited Models Limited", "project_url": "https://www.rockethub.com/projects/60303-start-up-support-for-comited-models-limited", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60303/1439240897-large.jpg", "id": "60303"}
{"website": 3, "end": "2015-10-31", "author": "Noemie", "type": 1, "pledged": "0", "title": "Humanitarian work for survival of animals", "project_url": "https://www.rockethub.com/projects/60368-humanitarian-work-for-survival-of-animals", "currency": "USD", "location": "no location", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60368/1439394159-large.jpg", "id": "60368"}
{"website": 3, "end": "2015-10-22", "author": "adam", "type": 1, "pledged": "0", "title": "Can I Have 100 Million Dollars, Please?", "project_url": "https://www.rockethub.com/projects/55317-can-i-have-100-million-dollars-please", "currency": "USD", "location": "no location", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/55317/1426954543-large.JPG", "id": "55317"}
{"website": 3, "end": "2015-10-22", "author": "adam", "type": 1, "pledged": "0", "title": "Can I Have 100 Million Dollars, Please?", "project_url": "https://www.rockethub.com/projects/55317-can-i-have-100-million-dollars-please", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/55317/1426954543-large.JPG", "id": "55317"}
{"website": 3, "end": "2015-10-17", "author": "Danie Lito", "type": 1, "pledged": "0", "title": "Nomad Tiny House", "project_url": "https://www.rockethub.com/projects/59677-nomad-tiny-house", "currency": "USD", "location": "Bucharest, Romania", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59677/1437398223-large.jpg", "id": "59677"}
{"website": 3, "end": "2015-10-17", "author": "Danie Lito", "type": 1, "pledged": "0", "title": "Nomad Tiny House", "project_url": "https://www.rockethub.com/projects/59677-nomad-tiny-house", "currency": "USD", "location": "Bucharest, Romania", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59677/1437398223-large.jpg", "id": "59677"}
{"website": 3, "end": "2015-10-17", "author": "Danie Lito", "type": 1, "pledged": "0", "title": "Nomad Tiny House", "project_url": "https://www.rockethub.com/projects/59677-nomad-tiny-house", "currency": "USD", "location": "Bucharest, Romania", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59677/1437398223-large.jpg", "id": "59677"}
{"website": 3, "end": "2015-10-17", "author": "Danie Lito", "type": 1, "pledged": "0", "title": "Nomad Tiny House", "project_url": "https://www.rockethub.com/projects/59677-nomad-tiny-house", "currency": "USD", "location": "Bucharest, Romania", "category_id": "3", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59677/1437398223-large.jpg", "id": "59677"}
{"website": 3, "end": "2015-10-17", "author": "Danie Lito", "type": 1, "pledged": "0", "title": "Nomad Tiny House", "project_url": "https://www.rockethub.com/projects/59677-nomad-tiny-house", "currency": "USD", "location": "Bucharest, Romania", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59677/1437398223-large.jpg", "id": "59677"}
{"website": 3, "end": "2015-10-17", "author": "Danie Lito", "type": 1, "pledged": "0", "title": "Nomad Tiny House", "project_url": "https://www.rockethub.com/projects/59677-nomad-tiny-house", "currency": "USD", "location": "Bucharest, Romania", "category_id": "12", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59677/1437398223-large.jpg", "id": "59677"}
{"website": 3, "end": "2015-10-17", "author": "Danie Lito", "type": 1, "pledged": "0", "title": "Nomad Tiny House", "project_url": "https://www.rockethub.com/projects/59677-nomad-tiny-house", "currency": "USD", "location": "Bucharest, Romania", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59677/1437398223-large.jpg", "id": "59677"}
{"website": 3, "end": "2015-10-17", "author": "Danie Lito", "type": 1, "pledged": "0", "title": "Nomad Tiny House", "project_url": "https://www.rockethub.com/projects/59677-nomad-tiny-house", "currency": "USD", "location": "Bucharest, Romania", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59677/1437398223-large.jpg", "id": "59677"}
{"website": 3, "end": "2015-10-19", "author": "Literacy Inc", "type": 1, "pledged": "0", "title": "Literacy Inc - Stay True to You", "project_url": "https://www.rockethub.com/projects/59720-literacy-inc-stay-true-to-you", "currency": "USD", "location": "Lafayette, LA", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59720/1437526662-large.jpg", "id": "59720"}
{"website": 3, "end": "2015-10-18", "author": "Jack Resweber", "type": 1, "pledged": "1582", "title": "Support the Development of Phonec for Mac and Windows 64-bit", "project_url": "https://www.rockethub.com/projects/61286-support-the-development-of-phonec-for-mac-and-windows-64-bit", "currency": "USD", "location": "New Orleans, LA", "category_id": "11", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61286/1442335905-large.jpg", "id": "61286"}
{"website": 3, "end": "2015-11-12", "author": "Wayne Fernandes", "type": 1, "pledged": "425", "title": "Zing Airlines", "project_url": "https://www.rockethub.com/projects/61446-zing-airlines", "currency": "USD", "location": "no location", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61446/1444358852-large.png", "id": "61446"}
{"website": 3, "end": "2015-10-30", "author": "Joy", "type": 1, "pledged": "0", "title": "Copenhagen - volunteer and study", "project_url": "https://www.rockethub.com/projects/62268-copenhagen-volunteer-and-study", "currency": "USD", "location": "Copenhagen , Denmark", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/62268/1444599116-large.jpeg", "id": "62268"}
{"website": 3, "end": "2015-10-30", "author": "Joy", "type": 1, "pledged": "0", "title": "Copenhagen - volunteer and study", "project_url": "https://www.rockethub.com/projects/62268-copenhagen-volunteer-and-study", "currency": "USD", "location": "Copenhagen , Denmark", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/62268/1444599116-large.jpeg", "id": "62268"}
{"website": 3, "end": "2015-11-10", "author": "Helena", "type": 1, "pledged": "0", "title": "The bank will get my home if i dont pay the loan.", "project_url": "https://www.rockethub.com/projects/61756-the-bank-will-get-my-home-if-i-dont-pay-the-loan", "currency": "USD", "location": "Athens, Greece", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61756/1443051072-large.jpg", "id": "61756"}
{"website": 3, "end": "2015-11-10", "author": "Helena", "type": 1, "pledged": "0", "title": "The bank will get my home if i dont pay the loan.", "project_url": "https://www.rockethub.com/projects/61756-the-bank-will-get-my-home-if-i-dont-pay-the-loan", "currency": "USD", "location": "Athens, Greece", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61756/1443051072-large.jpg", "id": "61756"}
{"website": 3, "end": "2015-11-10", "author": "Helena", "type": 1, "pledged": "0", "title": "The bank will get my home if i dont pay the loan.", "project_url": "https://www.rockethub.com/projects/61756-the-bank-will-get-my-home-if-i-dont-pay-the-loan", "currency": "USD", "location": "Athens, Greece", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61756/1443051072-large.jpg", "id": "61756"}
{"website": 3, "end": "2015-11-10", "author": "Helena", "type": 1, "pledged": "0", "title": "The bank will get my home if i dont pay the loan.", "project_url": "https://www.rockethub.com/projects/61756-the-bank-will-get-my-home-if-i-dont-pay-the-loan", "currency": "USD", "location": "Athens, Greece", "category_id": "3", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61756/1443051072-large.jpg", "id": "61756"}
{"website": 3, "end": "2015-11-10", "author": "Helena", "type": 1, "pledged": "0", "title": "The bank will get my home if i dont pay the loan.", "project_url": "https://www.rockethub.com/projects/61756-the-bank-will-get-my-home-if-i-dont-pay-the-loan", "currency": "USD", "location": "Athens, Greece", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61756/1443051072-large.jpg", "id": "61756"}
{"website": 3, "end": "2015-11-10", "author": "Helena", "type": 1, "pledged": "0", "title": "The bank will get my home if i dont pay the loan.", "project_url": "https://www.rockethub.com/projects/61756-the-bank-will-get-my-home-if-i-dont-pay-the-loan", "currency": "USD", "location": "Athens, Greece", "category_id": "12", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61756/1443051072-large.jpg", "id": "61756"}
{"website": 3, "end": "2015-11-10", "author": "Helena", "type": 1, "pledged": "0", "title": "The bank will get my home if i dont pay the loan.", "project_url": "https://www.rockethub.com/projects/61756-the-bank-will-get-my-home-if-i-dont-pay-the-loan", "currency": "USD", "location": "Athens, Greece", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61756/1443051072-large.jpg", "id": "61756"}
{"website": 3, "end": "2015-11-10", "author": "Helena", "type": 1, "pledged": "0", "title": "The bank will get my home if i dont pay the loan.", "project_url": "https://www.rockethub.com/projects/61756-the-bank-will-get-my-home-if-i-dont-pay-the-loan", "currency": "USD", "location": "Athens, Greece", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61756/1443051072-large.jpg", "id": "61756"}
{"website": 3, "end": "2015-12-02", "author": "Minjae Kim", "type": 1, "pledged": "0", "title": "MUNY", "project_url": "https://www.rockethub.com/projects/61991-muny", "currency": "USD", "location": "Seoul, Korea, Republic of", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61991/1443713065-large.jpg", "id": "61991"}
{"website": 3, "end": "2015-11-20", "author": "CourtCaseResults.com", "type": 1, "pledged": "0", "title": "CourtCaseResults.com: Support Our Public Record Lawyer Data Movement", "project_url": "https://www.rockethub.com/projects/60595-courtcaseresults-com-support-our-public-record-lawyer-data-movement", "currency": "USD", "location": "no location", "category_id": "11", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60595/1440029474-large.png", "id": "60595"}
{"website": 3, "end": "2015-11-20", "author": "CourtCaseResults.com", "type": 1, "pledged": "0", "title": "CourtCaseResults.com: Support Our Public Record Lawyer Data Movement", "project_url": "https://www.rockethub.com/projects/60595-courtcaseresults-com-support-our-public-record-lawyer-data-movement", "currency": "USD", "location": "no location", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60595/1440029474-large.png", "id": "60595"}
{"website": 3, "end": "2015-12-31", "author": "Nasya Kamrat", "type": 1, "pledged": "6616", "title": "UNSPEAKABLE: An Animated Holocaust Documentary", "project_url": "https://www.rockethub.com/projects/43758-unspeakable-an-animated-holocaust-documentary", "currency": "USD", "location": "no location", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/43758/1401759333-large.jpg", "id": "43758"}
{"website": 3, "end": "2015-11-08", "author": "Joan Bergmans", "type": 1, "pledged": "2362", "title": "Share the Stoke Foundation Portugal", "project_url": "https://www.rockethub.com/projects/59659-share-the-stoke-foundation-portugal", "currency": "USD", "location": "no location", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59659/1437296513-large.png", "id": "59659"}
{"website": 3, "end": "2015-11-08", "author": "Joan Bergmans", "type": 1, "pledged": "2362", "title": "Share the Stoke Foundation Portugal", "project_url": "https://www.rockethub.com/projects/59659-share-the-stoke-foundation-portugal", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59659/1437296513-large.png", "id": "59659"}
{"website": 3, "end": "2015-12-09", "author": "Wayde Fishman", "type": 1, "pledged": "3070", "title": "PRICE FOR PARADISE -The Struggles & Successes of living the Real Hawaii", "project_url": "https://www.rockethub.com/projects/58805-price-for-paradise-the-struggles-successes-of-living-the-real-hawaii", "currency": "USD", "location": "no location", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58805/1435718773-large.jpg", "id": "58805"}
{"website": 3, "end": "2015-12-09", "author": "Wayde Fishman", "type": 1, "pledged": "3070", "title": "PRICE FOR PARADISE -The Struggles & Successes of living the Real Hawaii", "project_url": "https://www.rockethub.com/projects/58805-price-for-paradise-the-struggles-successes-of-living-the-real-hawaii", "currency": "USD", "location": "no location", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58805/1435718773-large.jpg", "id": "58805"}
{"website": 3, "end": "2015-12-09", "author": "Wayde Fishman", "type": 1, "pledged": "3070", "title": "PRICE FOR PARADISE -The Struggles & Successes of living the Real Hawaii", "project_url": "https://www.rockethub.com/projects/58805-price-for-paradise-the-struggles-successes-of-living-the-real-hawaii", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58805/1435718773-large.jpg", "id": "58805"}
{"website": 3, "end": "2015-12-09", "author": "Wayde Fishman", "type": 1, "pledged": "3070", "title": "PRICE FOR PARADISE -The Struggles & Successes of living the Real Hawaii", "project_url": "https://www.rockethub.com/projects/58805-price-for-paradise-the-struggles-successes-of-living-the-real-hawaii", "currency": "USD", "location": "no location", "category_id": "3", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58805/1435718773-large.jpg", "id": "58805"}
{"website": 3, "end": "2015-12-09", "author": "Wayde Fishman", "type": 1, "pledged": "3070", "title": "PRICE FOR PARADISE -The Struggles & Successes of living the Real Hawaii", "project_url": "https://www.rockethub.com/projects/58805-price-for-paradise-the-struggles-successes-of-living-the-real-hawaii", "currency": "USD", "location": "no location", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58805/1435718773-large.jpg", "id": "58805"}
{"website": 3, "end": "2015-12-09", "author": "Wayde Fishman", "type": 1, "pledged": "3070", "title": "PRICE FOR PARADISE -The Struggles & Successes of living the Real Hawaii", "project_url": "https://www.rockethub.com/projects/58805-price-for-paradise-the-struggles-successes-of-living-the-real-hawaii", "currency": "USD", "location": "no location", "category_id": "12", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58805/1435718773-large.jpg", "id": "58805"}
{"website": 3, "end": "2015-12-09", "author": "Wayde Fishman", "type": 1, "pledged": "3070", "title": "PRICE FOR PARADISE -The Struggles & Successes of living the Real Hawaii", "project_url": "https://www.rockethub.com/projects/58805-price-for-paradise-the-struggles-successes-of-living-the-real-hawaii", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58805/1435718773-large.jpg", "id": "58805"}
{"website": 3, "end": "2015-12-09", "author": "Wayde Fishman", "type": 1, "pledged": "3070", "title": "PRICE FOR PARADISE -The Struggles & Successes of living the Real Hawaii", "project_url": "https://www.rockethub.com/projects/58805-price-for-paradise-the-struggles-successes-of-living-the-real-hawaii", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58805/1435718773-large.jpg", "id": "58805"}
{"website": 3, "end": "2015-11-30", "author": "Rupert Marshall-Luck", "type": 1, "pledged": "2695", "title": "Premi\u00e8re recording of British Romantic masterpieces", "project_url": "https://www.rockethub.com/projects/60297-premiere-recording-of-british-romantic-masterpieces", "currency": "USD", "location": "no location", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60297/1439226111-large.jpg", "id": "60297"}
{"website": 3, "end": "2015-11-15", "author": "alex ezorsky-lie", "type": 1, "pledged": "1655", "title": "Space Park", "project_url": "https://www.rockethub.com/projects/61957-space-park", "currency": "USD", "location": "Somerville, MA", "category_id": "11", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61957/1443978002-large.jpg", "id": "61957"}
{"website": 3, "end": "2015-11-15", "author": "alex ezorsky-lie", "type": 1, "pledged": "1655", "title": "Space Park", "project_url": "https://www.rockethub.com/projects/61957-space-park", "currency": "USD", "location": "Somerville, MA", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61957/1443978002-large.jpg", "id": "61957"}
{"website": 3, "end": "2015-10-23", "author": "Martin Colon", "type": 1, "pledged": "150", "title": "Color for Christopher", "project_url": "https://www.rockethub.com/projects/61236-color-for-christopher", "currency": "USD", "location": "no location", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61236/1442004048-large.gif", "id": "61236"}
{"website": 3, "end": "2015-11-08", "author": "Joan Bergmans", "type": 1, "pledged": "2362", "title": "Share the Stoke Foundation Portugal", "project_url": "https://www.rockethub.com/projects/59659-share-the-stoke-foundation-portugal", "currency": "USD", "location": "no location", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59659/1437296513-large.png", "id": "59659"}
{"website": 3, "end": "2015-11-08", "author": "Joan Bergmans", "type": 1, "pledged": "2362", "title": "Share the Stoke Foundation Portugal", "project_url": "https://www.rockethub.com/projects/59659-share-the-stoke-foundation-portugal", "currency": "USD", "location": "no location", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59659/1437296513-large.png", "id": "59659"}
{"website": 3, "end": "2015-11-08", "author": "Joan Bergmans", "type": 1, "pledged": "2362", "title": "Share the Stoke Foundation Portugal", "project_url": "https://www.rockethub.com/projects/59659-share-the-stoke-foundation-portugal", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59659/1437296513-large.png", "id": "59659"}
{"website": 3, "end": "2015-11-08", "author": "Joan Bergmans", "type": 1, "pledged": "2362", "title": "Share the Stoke Foundation Portugal", "project_url": "https://www.rockethub.com/projects/59659-share-the-stoke-foundation-portugal", "currency": "USD", "location": "no location", "category_id": "3", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59659/1437296513-large.png", "id": "59659"}
{"website": 3, "end": "2015-11-08", "author": "Joan Bergmans", "type": 1, "pledged": "2362", "title": "Share the Stoke Foundation Portugal", "project_url": "https://www.rockethub.com/projects/59659-share-the-stoke-foundation-portugal", "currency": "USD", "location": "no location", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59659/1437296513-large.png", "id": "59659"}
{"website": 3, "end": "2015-11-08", "author": "Joan Bergmans", "type": 1, "pledged": "2362", "title": "Share the Stoke Foundation Portugal", "project_url": "https://www.rockethub.com/projects/59659-share-the-stoke-foundation-portugal", "currency": "USD", "location": "no location", "category_id": "12", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59659/1437296513-large.png", "id": "59659"}
{"website": 3, "end": "2015-11-08", "author": "Joan Bergmans", "type": 1, "pledged": "2362", "title": "Share the Stoke Foundation Portugal", "project_url": "https://www.rockethub.com/projects/59659-share-the-stoke-foundation-portugal", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59659/1437296513-large.png", "id": "59659"}
{"website": 3, "end": "2015-11-08", "author": "Joan Bergmans", "type": 1, "pledged": "2362", "title": "Share the Stoke Foundation Portugal", "project_url": "https://www.rockethub.com/projects/59659-share-the-stoke-foundation-portugal", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59659/1437296513-large.png", "id": "59659"}
