{"end": "2015-10-06", "author": "Isabel Milenski", "title": "Floating Opera New York Pelleas and Melisande", "project_url": "https://www.rockethub.com/projects/60540-floating-opera-new-york-pelleas-and-melisande", "location": "Brooklyn, NY", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60540/1439865071-large.png", "id": "60540"}
{"end": "2015-10-28", "author": "Naomi Striemer", "title": "Naomi Striemer Album 2016!!", "project_url": "https://www.rockethub.com/projects/59968-naomi-striemer-album-2016", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59968/1438281789-large.jpg", "id": "59968"}
{"end": "2015-11-16", "author": "Deven Balsam", "title": "9th Phoenix Mobile DJ Service", "project_url": "https://www.rockethub.com/projects/60539-9th-phoenix-mobile-dj-service", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60539/1439918632-large.jpg", "id": "60539"}
{"end": "2015-10-12", "author": "Frances Drost", "title": "The Tip Jar - Fill Frances Drost's Musical Tip Jar in 2015", "project_url": "https://www.rockethub.com/projects/60711-the-tip-jar-fill-frances-drost-s-musical-tip-jar-in-2015", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60711/1440436045-large.jpg", "id": "60711"}
{"end": "2015-10-31", "author": "Joe Cristina", "title": "KidWorks Avanti Music Program", "project_url": "https://www.rockethub.com/projects/59922-kidworks-avanti-music-program", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59922/1439076763-large.png", "id": "59922"}
{"end": "2015-09-25", "author": "Brian Melick", "title": "Support Brian Melick Donating Fully Functional LEGO Drum Set to PAS Museum", "project_url": "https://www.rockethub.com/projects/60307-support-brian-melick-donating-fully-functional-lego-drum-set-to-pas-museum", "location": "New Baltimore, NY", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60307/1439246630-large.jpg", "id": "60307"}
{"end": "2015-09-15", "author": "Ashley Grant", "title": "Tunes & Tails: Spread the Love Fundraising Event!", "project_url": "https://www.rockethub.com/projects/60393-tunes-tails-spread-the-love-fundraising-event", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60393/1439481183-large.jpg", "id": "60393"}
{"end": "2015-10-10", "author": "eugenia arroyo", "title": "Get Cece to the Tampa Taylor Swift Concert!", "project_url": "https://www.rockethub.com/projects/60487-get-cece-to-the-tampa-taylor-swift-concert", "location": "Mar del Plata, Argentina", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60487/1439753492-large.jpg", "id": "60487"}
{"end": "2015-09-30", "author": "Sharla June", "title": "Shar-La-La Music Together", "project_url": "https://www.rockethub.com/projects/61092-shar-la-la-music-together", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61092/1441724860-large.jpg", "id": "61092"}
