{"end": "2015-09-13", "author": "Munro Driessen", "title": "Green Boat Men Fund", "project_url": "https://www.rockethub.com/projects/58707-green-boat-men-fund", "location": "Micronesia, Federated States of", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58707/1434849122-large.JPG", "id": "58707"}
{"end": "2015-09-20", "author": "Evgeny Durin", "title": "International goat\u2019s milk mega farm CAPELLA", "project_url": "https://www.rockethub.com/projects/59547-international-goat-s-milk-mega-farm-capella", "location": "Volgograd, Russian Federation", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59547/1436970022-large.jpg", "id": "59547"}
{"end": "2015-09-06", "author": "Simon Angelov", "title": "IceCreamZilla\u00ae: 24/7 Global \"On-Demand\" Ice Cream Delivery", "project_url": "https://www.rockethub.com/projects/58271-icecreamzilla-24-7-global-on-demand-ice-cream-delivery", "location": "no location", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58271/1433818217-large.jpg", "id": "58271"}
{"end": "2015-10-15", "author": "Sugar Free The Movie", "title": "Sugar Free The Movie- Break The Addiction", "project_url": "https://www.rockethub.com/projects/57823-sugar-free-the-movie-break-the-addiction", "location": "no location", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/57823/1436497057-large.jpg", "id": "57823"}
{"end": "2015-11-21", "author": "Emmanuel Chiduo", "title": "Smart Poultry Farming, (layer chickens for best quality eggs production).", "project_url": "https://www.rockethub.com/projects/60653-smart-poultry-farming-layer-chickens-for-best-quality-eggs-production", "location": "Morogoro, Tanzania, United Republic of", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60653/1440258226-large.jpg", "id": "60653"}
{"end": "2015-09-08", "author": "Jaques Bester", "title": "Wildhoneybush", "project_url": "https://www.rockethub.com/projects/57872-wildhoneybush", "location": "South Africa", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/57872/1433941739-large.jpg", "id": "57872"}
{"end": "2015-09-22", "author": "Lorna Doyle", "title": "Help fund my postgraduate studies and learn about athletes diet and health", "project_url": "https://www.rockethub.com/projects/58844-help-fund-my-postgraduate-studies-and-learn-about-athletes-diet-and-health", "location": "Carlow, Ireland", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58844/1435315703-large.jpg", "id": "58844"}
{"end": "2015-09-26", "author": "Tanya Pushkina", "title": "French Pastry Campus in ENSP", "project_url": "https://www.rockethub.com/projects/56377-french-pastry-campus-in-ensp", "location": "Sankt Petersburg, Russian Federation", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/56377/1429377421-large.jpg", "id": "56377"}
{"end": "2015-09-19", "author": "Jessika Cifuentes Anguiano", "title": "Single mother dream business", "project_url": "https://www.rockethub.com/projects/58738-single-mother-dream-business", "location": "Eagle Mountain, UT", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58738/1434935163-large.jpg", "id": "58738"}
