{"website": 3, "end": "2015-12-09", "author": "Wayde Fishman", "type": 1, "pledged": "3070", "title": "PRICE FOR PARADISE -The Struggles & Successes of living the Real Hawaii", "project_url": "https://www.rockethub.com/projects/58805-price-for-paradise-the-struggles-successes-of-living-the-real-hawaii", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58805/1435718773-large.jpg", "id": "58805"}
{"website": 3, "end": "2015-12-04", "author": "Von-Anise McCoy", "type": 1, "pledged": "350", "title": "Bougie Betty", "project_url": "https://www.rockethub.com/projects/60732-bougie-betty", "currency": "USD", "location": "New York , NY", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60732/1443728809-large.JPG", "id": "60732"}
{"website": 3, "end": "2015-10-20", "author": "Shako Khiski", "type": 1, "pledged": "3885", "title": "Help Shako Raise $3000 in 30 Days For His EP!", "project_url": "https://www.rockethub.com/projects/60660-help-shako-raise-3000-in-30-days-for-his-ep", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60660/1442533702-large.jpg", "id": "60660"}
{"website": 3, "end": "2015-10-17", "author": "Shirin Tinati", "type": 1, "pledged": "13355", "title": "\"I Am Warrior\" a Photo Book to Empower Women During Breast Cancer Treatment", "project_url": "https://www.rockethub.com/projects/60987-i-am-warrior-a-photo-book-to-empower-women-during-breast-cancer-treatment", "currency": "USD", "location": "no location", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60987/1444154811-large.png", "id": "60987"}
{"website": 3, "end": "2015-10-20", "author": "Shako Khiski", "type": 1, "pledged": "3885", "title": "Help Shako Raise $3000 in 30 Days For His EP!", "project_url": "https://www.rockethub.com/projects/60660-help-shako-raise-3000-in-30-days-for-his-ep", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60660/1442533702-large.jpg", "id": "60660"}
{"website": 3, "end": "2015-12-31", "author": "Nasya Kamrat", "type": 1, "pledged": "6616", "title": "UNSPEAKABLE: An Animated Holocaust Documentary", "project_url": "https://www.rockethub.com/projects/43758-unspeakable-an-animated-holocaust-documentary", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/43758/1401759333-large.jpg", "id": "43758"}
{"website": 3, "end": "2015-11-20", "author": "Steve Thornton", "type": 1, "pledged": "200", "title": "Help Stephen attend AND's November Per4mance Intensive Workshop", "project_url": "https://www.rockethub.com/projects/61621-help-stephen-attend-and-s-november-per4mance-intensive-workshop", "currency": "USD", "location": "Brooklyn, NY", "category_id": "12", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61621/1442776516-large.jpg", "id": "61621"}
{"website": 3, "end": "2015-11-09", "author": "Wyrd Theatre", "type": 1, "pledged": "1405", "title": "Support Wyrd Theatre's \"Tartuffe en Burlesque!\"", "project_url": "https://www.rockethub.com/projects/61413-support-wyrd-theatre-s-tartuffe-en-burlesque", "currency": "USD", "location": "no location", "category_id": "3", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61413/1444276531-large.jpg", "id": "61413"}
{"website": 3, "end": "2015-10-17", "author": "Shirin Tinati", "type": 1, "pledged": "13355", "title": "\"I Am Warrior\" a Photo Book to Empower Women During Breast Cancer Treatment", "project_url": "https://www.rockethub.com/projects/60987-i-am-warrior-a-photo-book-to-empower-women-during-breast-cancer-treatment", "currency": "USD", "location": "no location", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60987/1444154811-large.png", "id": "60987"}
{"website": 3, "end": "2015-11-02", "author": "Michael", "type": 1, "pledged": "0", "title": "Remembering the Void, Near Death Experiences and Out of Body States", "project_url": "https://www.rockethub.com/projects/60107-remembering-the-void-near-death-experiences-and-out-of-body-states", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60107/1438718077-large.jpg", "id": "60107"}
{"website": 3, "end": "2015-10-31", "author": "Brad L. Baird", "type": 1, "pledged": "35", "title": "\"Fred's Story\" - Family Hospitals & Senior Centres Book Placement Program", "project_url": "https://www.rockethub.com/projects/61531-fred-s-story-family-hospitals-senior-centres-book-placement-program", "currency": "USD", "location": "Edmonton, Canada", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61531/1442486052-large.jpg", "id": "61531"}
{"website": 3, "end": "2015-10-31", "author": "Brad L. Baird", "type": 1, "pledged": "35", "title": "\"Fred's Story\" - Family Hospitals & Senior Centres Book Placement Program", "project_url": "https://www.rockethub.com/projects/61531-fred-s-story-family-hospitals-senior-centres-book-placement-program", "currency": "USD", "location": "Edmonton, Canada", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61531/1442486052-large.jpg", "id": "61531"}
{"website": 3, "end": "2015-10-31", "author": "Brad L. Baird", "type": 1, "pledged": "35", "title": "\"Fred's Story\" - Family Hospitals & Senior Centres Book Placement Program", "project_url": "https://www.rockethub.com/projects/61531-fred-s-story-family-hospitals-senior-centres-book-placement-program", "currency": "USD", "location": "Edmonton, Canada", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61531/1442486052-large.jpg", "id": "61531"}
{"website": 3, "end": "2015-10-31", "author": "Brad L. Baird", "type": 1, "pledged": "35", "title": "\"Fred's Story\" - Family Hospitals & Senior Centres Book Placement Program", "project_url": "https://www.rockethub.com/projects/61531-fred-s-story-family-hospitals-senior-centres-book-placement-program", "currency": "USD", "location": "Edmonton, Canada", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61531/1442486052-large.jpg", "id": "61531"}
{"website": 3, "end": "2015-10-31", "author": "Brad L. Baird", "type": 1, "pledged": "35", "title": "\"Fred's Story\" - Family Hospitals & Senior Centres Book Placement Program", "project_url": "https://www.rockethub.com/projects/61531-fred-s-story-family-hospitals-senior-centres-book-placement-program", "currency": "USD", "location": "Edmonton, Canada", "category_id": "12", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61531/1442486052-large.jpg", "id": "61531"}
{"website": 3, "end": "2015-10-31", "author": "Brad L. Baird", "type": 1, "pledged": "35", "title": "\"Fred's Story\" - Family Hospitals & Senior Centres Book Placement Program", "project_url": "https://www.rockethub.com/projects/61531-fred-s-story-family-hospitals-senior-centres-book-placement-program", "currency": "USD", "location": "Edmonton, Canada", "category_id": "3", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61531/1442486052-large.jpg", "id": "61531"}
{"website": 3, "end": "2015-10-31", "author": "Brad L. Baird", "type": 1, "pledged": "35", "title": "\"Fred's Story\" - Family Hospitals & Senior Centres Book Placement Program", "project_url": "https://www.rockethub.com/projects/61531-fred-s-story-family-hospitals-senior-centres-book-placement-program", "currency": "USD", "location": "Edmonton, Canada", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61531/1442486052-large.jpg", "id": "61531"}
{"website": 3, "end": "2015-11-08", "author": "Scott Ambrose", "type": 1, "pledged": "130", "title": "The Sincerity Lodge Charity Christmas Tree for Kennedy Krieger Festival", "project_url": "https://www.rockethub.com/projects/61989-the-sincerity-lodge-charity-christmas-tree-for-kennedy-krieger-festival", "currency": "USD", "location": "Baltimore, MD", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61989/1444443463-large.jpg", "id": "61989"}
{"website": 3, "end": "2015-11-15", "author": "Karina Mirochnik", "type": 1, "pledged": "1410", "title": "Women Across Frontiers & MADRE - International Fundraising Initiative", "project_url": "https://www.rockethub.com/projects/59706-women-across-frontiers-madre-international-fundraising-initiative", "currency": "USD", "location": "no location", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59706/1437501826-large.jpg", "id": "59706"}
{"website": 3, "end": "2015-11-09", "author": "Laurie Carrigan", "type": 1, "pledged": "625", "title": "ACPW's Women in Transition Career Conference", "project_url": "https://www.rockethub.com/projects/61810-acpw-s-women-in-transition-career-conference", "currency": "USD", "location": "Quantico, Stafford, Va", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61810/1443163241-large.jpg", "id": "61810"}
{"website": 3, "end": "2015-11-08", "author": "Scott Ambrose", "type": 1, "pledged": "130", "title": "The Sincerity Lodge Charity Christmas Tree for Kennedy Krieger Festival", "project_url": "https://www.rockethub.com/projects/61989-the-sincerity-lodge-charity-christmas-tree-for-kennedy-krieger-festival", "currency": "USD", "location": "Baltimore, MD", "category_id": "4", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61989/1444443463-large.jpg", "id": "61989"}
{"website": 3, "end": "2016-01-17", "author": "Penn State Lunar Lion Team", "type": 1, "pledged": "172452", "title": "Lunar Lion - the first ever university-led mission to the Moon", "project_url": "https://www.rockethub.com/projects/34210-lunar-lion-the-first-ever-university-led-mission-to-the-moon", "currency": "USD", "location": "University Park, PA", "category_id": "14", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/34210/1389827818-large.jpg", "id": "34210"}
{"website": 3, "end": "2015-10-23", "author": "Eleonore Nitzschke", "type": 1, "pledged": "5", "title": "The spiral of adventure", "project_url": "https://www.rockethub.com/projects/59779-the-spiral-of-adventure", "currency": "USD", "location": "New York City , NY", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59779/1437681001-large.JPG", "id": "59779"}
{"website": 3, "end": "2015-10-17", "author": "Shirin Tinati", "type": 1, "pledged": "13355", "title": "\"I Am Warrior\" a Photo Book to Empower Women During Breast Cancer Treatment", "project_url": "https://www.rockethub.com/projects/60987-i-am-warrior-a-photo-book-to-empower-women-during-breast-cancer-treatment", "currency": "USD", "location": "no location", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60987/1444154811-large.png", "id": "60987"}
{"website": 3, "end": "2015-12-31", "author": "Nasya Kamrat", "type": 1, "pledged": "6616", "title": "UNSPEAKABLE: An Animated Holocaust Documentary", "project_url": "https://www.rockethub.com/projects/43758-unspeakable-an-animated-holocaust-documentary", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/43758/1401759333-large.jpg", "id": "43758"}
{"website": 3, "end": "2015-10-29", "author": "Celia", "type": 1, "pledged": "30", "title": "When life gives you lemons - supporting young people with mental illnesses", "project_url": "https://www.rockethub.com/projects/61600-when-life-gives-you-lemons-supporting-young-people-with-mental-illnesses", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61600/1442702959-large.jpg", "id": "61600"}
{"website": 3, "end": "2015-10-31", "author": "Sugar Free The Movie", "type": 1, "pledged": "1201", "title": "Sugar Free The Movie- Break The Addiction", "project_url": "https://www.rockethub.com/projects/57823-sugar-free-the-movie-break-the-addiction", "currency": "USD", "location": "no location", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/57823/1436497057-large.jpg", "id": "57823"}
{"website": 3, "end": "2015-10-29", "author": "Tamika Tillis", "type": 1, "pledged": "0", "title": "$5 Challenge to house homeless", "project_url": "https://www.rockethub.com/projects/60011-5-challenge-to-house-homeless", "currency": "USD", "location": "Sacramento , Ca", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60011/1438389869-large.jpg", "id": "60011"}
{"website": 3, "end": "2015-10-29", "author": "Tamika Tillis", "type": 1, "pledged": "0", "title": "$5 Challenge to house homeless", "project_url": "https://www.rockethub.com/projects/60011-5-challenge-to-house-homeless", "currency": "USD", "location": "Sacramento , Ca", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60011/1438389869-large.jpg", "id": "60011"}
{"website": 3, "end": "2015-10-29", "author": "Tamika Tillis", "type": 1, "pledged": "0", "title": "$5 Challenge to house homeless", "project_url": "https://www.rockethub.com/projects/60011-5-challenge-to-house-homeless", "currency": "USD", "location": "Sacramento , Ca", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60011/1438389869-large.jpg", "id": "60011"}
{"website": 3, "end": "2015-10-29", "author": "Tamika Tillis", "type": 1, "pledged": "0", "title": "$5 Challenge to house homeless", "project_url": "https://www.rockethub.com/projects/60011-5-challenge-to-house-homeless", "currency": "USD", "location": "Sacramento , Ca", "category_id": "12", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60011/1438389869-large.jpg", "id": "60011"}
{"website": 3, "end": "2015-10-29", "author": "Tamika Tillis", "type": 1, "pledged": "0", "title": "$5 Challenge to house homeless", "project_url": "https://www.rockethub.com/projects/60011-5-challenge-to-house-homeless", "currency": "USD", "location": "Sacramento , Ca", "category_id": "3", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60011/1438389869-large.jpg", "id": "60011"}
{"website": 3, "end": "2015-10-29", "author": "Tamika Tillis", "type": 1, "pledged": "0", "title": "$5 Challenge to house homeless", "project_url": "https://www.rockethub.com/projects/60011-5-challenge-to-house-homeless", "currency": "USD", "location": "Sacramento , Ca", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60011/1438389869-large.jpg", "id": "60011"}
{"website": 3, "end": "2015-10-20", "author": "Chad Fields", "type": 1, "pledged": "0", "title": "Development of Personal Smart Blender and App that Weighs Contents!!", "project_url": "https://www.rockethub.com/projects/59743-development-of-personal-smart-blender-and-app-that-weighs-contents", "currency": "USD", "location": "Duncanville, TX", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59743/1437595483-large.jpg", "id": "59743"}
{"website": 3, "end": "2015-10-20", "author": "Chad Fields", "type": 1, "pledged": "0", "title": "Development of Personal Smart Blender and App that Weighs Contents!!", "project_url": "https://www.rockethub.com/projects/59743-development-of-personal-smart-blender-and-app-that-weighs-contents", "currency": "USD", "location": "Duncanville, TX", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59743/1437595483-large.jpg", "id": "59743"}
{"website": 3, "end": "2015-10-20", "author": "Chad Fields", "type": 1, "pledged": "0", "title": "Development of Personal Smart Blender and App that Weighs Contents!!", "project_url": "https://www.rockethub.com/projects/59743-development-of-personal-smart-blender-and-app-that-weighs-contents", "currency": "USD", "location": "Duncanville, TX", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59743/1437595483-large.jpg", "id": "59743"}
{"website": 3, "end": "2015-10-20", "author": "Chad Fields", "type": 1, "pledged": "0", "title": "Development of Personal Smart Blender and App that Weighs Contents!!", "project_url": "https://www.rockethub.com/projects/59743-development-of-personal-smart-blender-and-app-that-weighs-contents", "currency": "USD", "location": "Duncanville, TX", "category_id": "4", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59743/1437595483-large.jpg", "id": "59743"}
{"website": 3, "end": "2015-10-20", "author": "Chad Fields", "type": 1, "pledged": "0", "title": "Development of Personal Smart Blender and App that Weighs Contents!!", "project_url": "https://www.rockethub.com/projects/59743-development-of-personal-smart-blender-and-app-that-weighs-contents", "currency": "USD", "location": "Duncanville, TX", "category_id": "14", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59743/1437595483-large.jpg", "id": "59743"}
{"website": 3, "end": "2015-10-20", "author": "Chad Fields", "type": 1, "pledged": "0", "title": "Development of Personal Smart Blender and App that Weighs Contents!!", "project_url": "https://www.rockethub.com/projects/59743-development-of-personal-smart-blender-and-app-that-weighs-contents", "currency": "USD", "location": "Duncanville, TX", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59743/1437595483-large.jpg", "id": "59743"}
{"website": 3, "end": "2015-10-20", "author": "Chad Fields", "type": 1, "pledged": "0", "title": "Development of Personal Smart Blender and App that Weighs Contents!!", "project_url": "https://www.rockethub.com/projects/59743-development-of-personal-smart-blender-and-app-that-weighs-contents", "currency": "USD", "location": "Duncanville, TX", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59743/1437595483-large.jpg", "id": "59743"}
{"website": 3, "end": "2015-10-24", "author": "Tommi Linn Livingston", "type": 1, "pledged": "0", "title": "Support for Resturant Business - Saucy Witch", "project_url": "https://www.rockethub.com/projects/59850-support-for-resturant-business-saucy-witch", "currency": "USD", "location": "Salem, MA", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59850/1437951742-large.", "id": "59850"}
{"website": 3, "end": "2015-11-21", "author": "Emmanuel Chiduo", "type": 1, "pledged": "100", "title": "Smart Poultry Farming, (layer chickens for best quality eggs production).", "project_url": "https://www.rockethub.com/projects/60653-smart-poultry-farming-layer-chickens-for-best-quality-eggs-production", "currency": "USD", "location": "Morogoro, Tanzania, United Republic of", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60653/1440258226-large.jpg", "id": "60653"}
{"website": 3, "end": "2015-10-20", "author": "Chad Fields", "type": 1, "pledged": "0", "title": "Development of Personal Smart Blender and App that Weighs Contents!!", "project_url": "https://www.rockethub.com/projects/59743-development-of-personal-smart-blender-and-app-that-weighs-contents", "currency": "USD", "location": "Duncanville, TX", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59743/1437595483-large.jpg", "id": "59743"}
{"website": 3, "end": "2016-01-17", "author": "Penn State Lunar Lion Team", "type": 1, "pledged": "172452", "title": "Lunar Lion - the first ever university-led mission to the Moon", "project_url": "https://www.rockethub.com/projects/34210-lunar-lion-the-first-ever-university-led-mission-to-the-moon", "currency": "USD", "location": "University Park, PA", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/34210/1389827818-large.jpg", "id": "34210"}
{"website": 3, "end": "2015-10-31", "author": "Dennis Nakamura", "type": 1, "pledged": "200", "title": "Cosmo Pen and Cartridges", "project_url": "https://www.rockethub.com/projects/44024-cosmo-pen-and-cartridges", "currency": "USD", "location": "no location", "category_id": "5", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/44024/1401485868-large.jpg", "id": "44024"}
{"website": 3, "end": "2015-10-29", "author": "Tomasz Trzcinski", "type": 1, "pledged": "10", "title": "I would like to help charities", "project_url": "https://www.rockethub.com/projects/60000-i-would-like-to-help-charities", "currency": "USD", "location": "Szczytno, Poland", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60000/1438361076-large.jpg", "id": "60000"}
{"website": 3, "end": "2015-10-18", "author": "Jack Resweber", "type": 1, "pledged": "1582", "title": "Support the Development of Phonec for Mac and Windows 64-bit", "project_url": "https://www.rockethub.com/projects/61286-support-the-development-of-phonec-for-mac-and-windows-64-bit", "currency": "USD", "location": "New Orleans, LA", "category_id": "11", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61286/1442335905-large.jpg", "id": "61286"}
{"website": 3, "end": "2015-11-12", "author": "Wayne Fernandes", "type": 1, "pledged": "425", "title": "Zing Airlines", "project_url": "https://www.rockethub.com/projects/61446-zing-airlines", "currency": "USD", "location": "no location", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61446/1444358852-large.png", "id": "61446"}
{"website": 3, "end": "2015-12-31", "author": "Nasya Kamrat", "type": 1, "pledged": "6616", "title": "UNSPEAKABLE: An Animated Holocaust Documentary", "project_url": "https://www.rockethub.com/projects/43758-unspeakable-an-animated-holocaust-documentary", "currency": "USD", "location": "no location", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/43758/1401759333-large.jpg", "id": "43758"}
{"website": 3, "end": "2015-10-23", "author": "Kim Sinton", "type": 1, "pledged": "1", "title": "Global Warming Game", "project_url": "https://www.rockethub.com/projects/59824-global-warming-game", "currency": "USD", "location": "Alameda, CA", "category_id": "7", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59824/1437848338-large.png", "id": "59824"}
{"website": 3, "end": "2015-10-20", "author": "Christian Julch", "type": 1, "pledged": "0", "title": "Age Of Hunters : Dawn of Man", "project_url": "https://www.rockethub.com/projects/59722-age-of-hunters-dawn-of-man", "currency": "USD", "location": "no location", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59722/1437548344-large.jpg", "id": "59722"}
{"website": 3, "end": "2015-10-20", "author": "Christian Julch", "type": 1, "pledged": "0", "title": "Age Of Hunters : Dawn of Man", "project_url": "https://www.rockethub.com/projects/59722-age-of-hunters-dawn-of-man", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59722/1437548344-large.jpg", "id": "59722"}
{"website": 3, "end": "2015-10-20", "author": "Christian Julch", "type": 1, "pledged": "0", "title": "Age Of Hunters : Dawn of Man", "project_url": "https://www.rockethub.com/projects/59722-age-of-hunters-dawn-of-man", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59722/1437548344-large.jpg", "id": "59722"}
{"website": 3, "end": "2015-10-20", "author": "Christian Julch", "type": 1, "pledged": "0", "title": "Age Of Hunters : Dawn of Man", "project_url": "https://www.rockethub.com/projects/59722-age-of-hunters-dawn-of-man", "currency": "USD", "location": "no location", "category_id": "12", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59722/1437548344-large.jpg", "id": "59722"}
{"website": 3, "end": "2015-10-20", "author": "Christian Julch", "type": 1, "pledged": "0", "title": "Age Of Hunters : Dawn of Man", "project_url": "https://www.rockethub.com/projects/59722-age-of-hunters-dawn-of-man", "currency": "USD", "location": "no location", "category_id": "3", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59722/1437548344-large.jpg", "id": "59722"}
{"website": 3, "end": "2015-10-20", "author": "Christian Julch", "type": 1, "pledged": "0", "title": "Age Of Hunters : Dawn of Man", "project_url": "https://www.rockethub.com/projects/59722-age-of-hunters-dawn-of-man", "currency": "USD", "location": "no location", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59722/1437548344-large.jpg", "id": "59722"}
{"website": 3, "end": "2015-11-28", "author": "PETER YU", "type": 1, "pledged": "0", "title": "JetOne Motion - World's Most Advanced Simulation Center", "project_url": "https://www.rockethub.com/projects/60925-jetone-motion-world-s-most-advanced-simulation-center", "currency": "USD", "location": "Central, Hong Kong", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60925/1440998561-large.JPG", "id": "60925"}
{"website": 3, "end": "2015-11-28", "author": "PETER YU", "type": 1, "pledged": "0", "title": "JetOne Motion - World's Most Advanced Simulation Center", "project_url": "https://www.rockethub.com/projects/60925-jetone-motion-world-s-most-advanced-simulation-center", "currency": "USD", "location": "Central, Hong Kong", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60925/1440998561-large.JPG", "id": "60925"}
{"website": 3, "end": "2015-11-28", "author": "PETER YU", "type": 1, "pledged": "0", "title": "JetOne Motion - World's Most Advanced Simulation Center", "project_url": "https://www.rockethub.com/projects/60925-jetone-motion-world-s-most-advanced-simulation-center", "currency": "USD", "location": "Central, Hong Kong", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60925/1440998561-large.JPG", "id": "60925"}
{"website": 3, "end": "2015-11-28", "author": "PETER YU", "type": 1, "pledged": "0", "title": "JetOne Motion - World's Most Advanced Simulation Center", "project_url": "https://www.rockethub.com/projects/60925-jetone-motion-world-s-most-advanced-simulation-center", "currency": "USD", "location": "Central, Hong Kong", "category_id": "4", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60925/1440998561-large.JPG", "id": "60925"}
{"website": 3, "end": "2015-11-28", "author": "PETER YU", "type": 1, "pledged": "0", "title": "JetOne Motion - World's Most Advanced Simulation Center", "project_url": "https://www.rockethub.com/projects/60925-jetone-motion-world-s-most-advanced-simulation-center", "currency": "USD", "location": "Central, Hong Kong", "category_id": "14", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60925/1440998561-large.JPG", "id": "60925"}
{"website": 3, "end": "2015-11-28", "author": "PETER YU", "type": 1, "pledged": "0", "title": "JetOne Motion - World's Most Advanced Simulation Center", "project_url": "https://www.rockethub.com/projects/60925-jetone-motion-world-s-most-advanced-simulation-center", "currency": "USD", "location": "Central, Hong Kong", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60925/1440998561-large.JPG", "id": "60925"}
{"website": 3, "end": "2015-11-28", "author": "PETER YU", "type": 1, "pledged": "0", "title": "JetOne Motion - World's Most Advanced Simulation Center", "project_url": "https://www.rockethub.com/projects/60925-jetone-motion-world-s-most-advanced-simulation-center", "currency": "USD", "location": "Central, Hong Kong", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60925/1440998561-large.JPG", "id": "60925"}
{"website": 3, "end": "2015-12-01", "author": "Chris Rosenthal", "type": 1, "pledged": "0", "title": "Building a YouTube Gaming Channel", "project_url": "https://www.rockethub.com/projects/61002-building-a-youtube-gaming-channel", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61002/1441186664-large.jpg", "id": "61002"}
{"website": 3, "end": "2015-11-13", "author": "Aditya Guha", "type": 1, "pledged": "0", "title": "Quad : 4 Player Chess", "project_url": "https://www.rockethub.com/projects/60450-quad-4-player-chess", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60450/1439678569-large.jpg", "id": "60450"}
{"website": 3, "end": "2015-11-07", "author": "Joan Bergmans", "type": 1, "pledged": "2362", "title": "Share the Stoke Foundation Portugal", "project_url": "https://www.rockethub.com/projects/59659-share-the-stoke-foundation-portugal", "currency": "USD", "location": "no location", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59659/1437296513-large.png", "id": "59659"}
{"website": 3, "end": "2015-11-27", "author": "Jordan Bettencourt", "type": 1, "pledged": "0", "title": "Larger Dirtbike Needed", "project_url": "https://www.rockethub.com/projects/60350-larger-dirtbike-needed", "currency": "USD", "location": "no location", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60350/1439321553-large.jpg", "id": "60350"}
{"website": 3, "end": "2015-10-28", "author": "Ferron Morgan II", "type": 1, "pledged": "0", "title": "Grassroots Basketball Academy", "project_url": "https://www.rockethub.com/projects/59978-grassroots-basketball-academy", "currency": "USD", "location": "Denver, CO", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59978/1438307865-large.jpg", "id": "59978"}
{"website": 3, "end": "2015-10-28", "author": "Ferron Morgan II", "type": 1, "pledged": "0", "title": "Grassroots Basketball Academy", "project_url": "https://www.rockethub.com/projects/59978-grassroots-basketball-academy", "currency": "USD", "location": "Denver, CO", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59978/1438307865-large.jpg", "id": "59978"}
{"website": 3, "end": "2015-10-28", "author": "Ferron Morgan II", "type": 1, "pledged": "0", "title": "Grassroots Basketball Academy", "project_url": "https://www.rockethub.com/projects/59978-grassroots-basketball-academy", "currency": "USD", "location": "Denver, CO", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59978/1438307865-large.jpg", "id": "59978"}
{"website": 3, "end": "2015-10-28", "author": "Ferron Morgan II", "type": 1, "pledged": "0", "title": "Grassroots Basketball Academy", "project_url": "https://www.rockethub.com/projects/59978-grassroots-basketball-academy", "currency": "USD", "location": "Denver, CO", "category_id": "12", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59978/1438307865-large.jpg", "id": "59978"}
{"website": 3, "end": "2015-10-28", "author": "Ferron Morgan II", "type": 1, "pledged": "0", "title": "Grassroots Basketball Academy", "project_url": "https://www.rockethub.com/projects/59978-grassroots-basketball-academy", "currency": "USD", "location": "Denver, CO", "category_id": "3", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59978/1438307865-large.jpg", "id": "59978"}
{"website": 3, "end": "2015-10-28", "author": "Ferron Morgan II", "type": 1, "pledged": "0", "title": "Grassroots Basketball Academy", "project_url": "https://www.rockethub.com/projects/59978-grassroots-basketball-academy", "currency": "USD", "location": "Denver, CO", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59978/1438307865-large.jpg", "id": "59978"}
{"website": 3, "end": "2015-10-19", "author": "Mallorca Handbike Tour", "type": 1, "pledged": "5", "title": "Mallorca Handbike Tour", "project_url": "https://www.rockethub.com/projects/59542-mallorca-handbike-tour", "currency": "USD", "location": "Mallorca, Spain", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59542/1436951905-large.JPG", "id": "59542"}
{"website": 3, "end": "2015-10-19", "author": "Mallorca Handbike Tour", "type": 1, "pledged": "5", "title": "Mallorca Handbike Tour", "project_url": "https://www.rockethub.com/projects/59542-mallorca-handbike-tour", "currency": "USD", "location": "Mallorca, Spain", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59542/1436951905-large.JPG", "id": "59542"}
{"website": 3, "end": "2015-10-19", "author": "Mallorca Handbike Tour", "type": 1, "pledged": "5", "title": "Mallorca Handbike Tour", "project_url": "https://www.rockethub.com/projects/59542-mallorca-handbike-tour", "currency": "USD", "location": "Mallorca, Spain", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59542/1436951905-large.JPG", "id": "59542"}
{"website": 3, "end": "2015-10-19", "author": "Mallorca Handbike Tour", "type": 1, "pledged": "5", "title": "Mallorca Handbike Tour", "project_url": "https://www.rockethub.com/projects/59542-mallorca-handbike-tour", "currency": "USD", "location": "Mallorca, Spain", "category_id": "4", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59542/1436951905-large.JPG", "id": "59542"}
{"website": 3, "end": "2015-10-19", "author": "Mallorca Handbike Tour", "type": 1, "pledged": "5", "title": "Mallorca Handbike Tour", "project_url": "https://www.rockethub.com/projects/59542-mallorca-handbike-tour", "currency": "USD", "location": "Mallorca, Spain", "category_id": "14", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59542/1436951905-large.JPG", "id": "59542"}
{"website": 3, "end": "2015-10-19", "author": "Mallorca Handbike Tour", "type": 1, "pledged": "5", "title": "Mallorca Handbike Tour", "project_url": "https://www.rockethub.com/projects/59542-mallorca-handbike-tour", "currency": "USD", "location": "Mallorca, Spain", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59542/1436951905-large.JPG", "id": "59542"}
{"website": 3, "end": "2015-10-19", "author": "Mallorca Handbike Tour", "type": 1, "pledged": "5", "title": "Mallorca Handbike Tour", "project_url": "https://www.rockethub.com/projects/59542-mallorca-handbike-tour", "currency": "USD", "location": "Mallorca, Spain", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59542/1436951905-large.JPG", "id": "59542"}
{"website": 3, "end": "2015-10-30", "author": "Rusty Pearman", "type": 1, "pledged": "25", "title": "Helping Heroes with Hang 'Em High Outdoors", "project_url": "https://www.rockethub.com/projects/61519-helping-heroes-with-hang-em-high-outdoors", "currency": "USD", "location": "Medford, Oklahoma", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61519/1442431676-large.png", "id": "61519"}
{"website": 3, "end": "2015-10-31", "author": "Martin Gregor", "type": 1, "pledged": "0", "title": "Utopie klub - sports and leisure center", "project_url": "https://www.rockethub.com/projects/60604-utopie-klub-sports-and-leisure-center", "currency": "USD", "location": "Karlovy Vary, Czech Republic", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60604/1440057918-large.jpg", "id": "60604"}
{"website": 3, "end": "2015-11-07", "author": "Joan Bergmans", "type": 1, "pledged": "2362", "title": "Share the Stoke Foundation Portugal", "project_url": "https://www.rockethub.com/projects/59659-share-the-stoke-foundation-portugal", "currency": "USD", "location": "no location", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59659/1437296513-large.png", "id": "59659"}
{"website": 3, "end": "2015-10-26", "author": "Giftis", "type": 1, "pledged": "0", "title": "GIFTIS-when you need a handmade gift!", "project_url": "https://www.rockethub.com/projects/59945-giftis-when-you-need-a-handmade-gift", "currency": "USD", "location": "Vilnius, Lithuania", "category_id": "11", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59945/1438200636-large.jpg", "id": "59945"}
{"website": 3, "end": "2015-11-12", "author": "David Aaron", "type": 1, "pledged": "0", "title": "Job Swell app creation", "project_url": "https://www.rockethub.com/projects/60421-job-swell-app-creation", "currency": "USD", "location": "Sunnyside, NY", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60421/1439581241-large.jpg", "id": "60421"}
{"website": 3, "end": "2015-11-10", "author": "Helena", "type": 1, "pledged": "0", "title": "The bank will get my home if i dont pay the loan.", "project_url": "https://www.rockethub.com/projects/61756-the-bank-will-get-my-home-if-i-dont-pay-the-loan", "currency": "USD", "location": "Athens, Greece", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61756/1443051072-large.jpg", "id": "61756"}
{"website": 3, "end": "2015-11-10", "author": "Helena", "type": 1, "pledged": "0", "title": "The bank will get my home if i dont pay the loan.", "project_url": "https://www.rockethub.com/projects/61756-the-bank-will-get-my-home-if-i-dont-pay-the-loan", "currency": "USD", "location": "Athens, Greece", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61756/1443051072-large.jpg", "id": "61756"}
{"website": 3, "end": "2015-11-10", "author": "Helena", "type": 1, "pledged": "0", "title": "The bank will get my home if i dont pay the loan.", "project_url": "https://www.rockethub.com/projects/61756-the-bank-will-get-my-home-if-i-dont-pay-the-loan", "currency": "USD", "location": "Athens, Greece", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61756/1443051072-large.jpg", "id": "61756"}
{"website": 3, "end": "2015-11-10", "author": "Helena", "type": 1, "pledged": "0", "title": "The bank will get my home if i dont pay the loan.", "project_url": "https://www.rockethub.com/projects/61756-the-bank-will-get-my-home-if-i-dont-pay-the-loan", "currency": "USD", "location": "Athens, Greece", "category_id": "12", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61756/1443051072-large.jpg", "id": "61756"}
{"website": 3, "end": "2015-11-10", "author": "Helena", "type": 1, "pledged": "0", "title": "The bank will get my home if i dont pay the loan.", "project_url": "https://www.rockethub.com/projects/61756-the-bank-will-get-my-home-if-i-dont-pay-the-loan", "currency": "USD", "location": "Athens, Greece", "category_id": "3", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61756/1443051072-large.jpg", "id": "61756"}
{"website": 3, "end": "2015-11-10", "author": "Helena", "type": 1, "pledged": "0", "title": "The bank will get my home if i dont pay the loan.", "project_url": "https://www.rockethub.com/projects/61756-the-bank-will-get-my-home-if-i-dont-pay-the-loan", "currency": "USD", "location": "Athens, Greece", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61756/1443051072-large.jpg", "id": "61756"}
{"website": 3, "end": "2015-11-14", "author": "Bobby Marin", "type": 1, "pledged": "0", "title": "Help Bobby Marin with ongoing treatment costs", "project_url": "https://www.rockethub.com/projects/60492-help-bobby-marin-with-ongoing-treatment-costs", "currency": "USD", "location": "Kansas City, MO", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60492/1439771882-large.jpg", "id": "60492"}
{"website": 3, "end": "2015-11-14", "author": "Bobby Marin", "type": 1, "pledged": "0", "title": "Help Bobby Marin with ongoing treatment costs", "project_url": "https://www.rockethub.com/projects/60492-help-bobby-marin-with-ongoing-treatment-costs", "currency": "USD", "location": "Kansas City, MO", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60492/1439771882-large.jpg", "id": "60492"}
{"website": 3, "end": "2015-11-14", "author": "Bobby Marin", "type": 1, "pledged": "0", "title": "Help Bobby Marin with ongoing treatment costs", "project_url": "https://www.rockethub.com/projects/60492-help-bobby-marin-with-ongoing-treatment-costs", "currency": "USD", "location": "Kansas City, MO", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60492/1439771882-large.jpg", "id": "60492"}
{"website": 3, "end": "2015-11-14", "author": "Bobby Marin", "type": 1, "pledged": "0", "title": "Help Bobby Marin with ongoing treatment costs", "project_url": "https://www.rockethub.com/projects/60492-help-bobby-marin-with-ongoing-treatment-costs", "currency": "USD", "location": "Kansas City, MO", "category_id": "4", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60492/1439771882-large.jpg", "id": "60492"}
{"website": 3, "end": "2015-11-14", "author": "Bobby Marin", "type": 1, "pledged": "0", "title": "Help Bobby Marin with ongoing treatment costs", "project_url": "https://www.rockethub.com/projects/60492-help-bobby-marin-with-ongoing-treatment-costs", "currency": "USD", "location": "Kansas City, MO", "category_id": "14", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60492/1439771882-large.jpg", "id": "60492"}
{"website": 3, "end": "2015-11-14", "author": "Bobby Marin", "type": 1, "pledged": "0", "title": "Help Bobby Marin with ongoing treatment costs", "project_url": "https://www.rockethub.com/projects/60492-help-bobby-marin-with-ongoing-treatment-costs", "currency": "USD", "location": "Kansas City, MO", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60492/1439771882-large.jpg", "id": "60492"}
{"website": 3, "end": "2015-11-14", "author": "Bobby Marin", "type": 1, "pledged": "0", "title": "Help Bobby Marin with ongoing treatment costs", "project_url": "https://www.rockethub.com/projects/60492-help-bobby-marin-with-ongoing-treatment-costs", "currency": "USD", "location": "Kansas City, MO", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60492/1439771882-large.jpg", "id": "60492"}
{"website": 3, "end": "2015-11-18", "author": "Wamani James", "type": 1, "pledged": "0", "title": "Entuuha lending and saving club", "project_url": "https://www.rockethub.com/projects/60621-entuuha-lending-and-saving-club", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60621/1440115585-large.jpg", "id": "60621"}
{"website": 3, "end": "2015-10-25", "author": "Aditya Guha", "type": 1, "pledged": "0", "title": "The Perspective", "project_url": "https://www.rockethub.com/projects/60435-the-perspective", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60435/1439617981-large.jpg", "id": "60435"}
{"website": 3, "end": "2015-11-01", "author": "Catherine Matsuura", "type": 1, "pledged": "0", "title": "Indie Rize", "project_url": "https://www.rockethub.com/projects/60785-indie-rize", "currency": "USD", "location": "Portland, OR", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60785/1440606511-large.jpg", "id": "60785"}
{"website": 3, "end": "2015-11-01", "author": "Catherine Matsuura", "type": 1, "pledged": "0", "title": "Indie Rize", "project_url": "https://www.rockethub.com/projects/60785-indie-rize", "currency": "USD", "location": "Portland, OR", "category_id": "11", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60785/1440606511-large.jpg", "id": "60785"}
{"website": 3, "end": "2015-11-25", "author": "Kelly", "type": 1, "pledged": "0", "title": "USCountry Music", "project_url": "https://www.rockethub.com/projects/60810-uscountry-music", "currency": "USD", "location": "no location", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60810/1440676843-large.jpg", "id": "60810"}
{"website": 3, "end": "2015-11-21", "author": "Bryden Legg", "type": 1, "pledged": "0", "title": "Bryden Legg (Playlist Productions) Needs Gear. (no more renting)", "project_url": "https://www.rockethub.com/projects/56752-bryden-legg-playlist-productions-needs-gear-no-more-renting", "currency": "USD", "location": "Wetumpka, AL", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/56752/1430099177-large.jpg", "id": "56752"}
{"website": 3, "end": "2015-11-21", "author": "Bryden Legg", "type": 1, "pledged": "0", "title": "Bryden Legg (Playlist Productions) Needs Gear. (no more renting)", "project_url": "https://www.rockethub.com/projects/56752-bryden-legg-playlist-productions-needs-gear-no-more-renting", "currency": "USD", "location": "Wetumpka, AL", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/56752/1430099177-large.jpg", "id": "56752"}
{"website": 3, "end": "2015-11-21", "author": "Bryden Legg", "type": 1, "pledged": "0", "title": "Bryden Legg (Playlist Productions) Needs Gear. (no more renting)", "project_url": "https://www.rockethub.com/projects/56752-bryden-legg-playlist-productions-needs-gear-no-more-renting", "currency": "USD", "location": "Wetumpka, AL", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/56752/1430099177-large.jpg", "id": "56752"}
{"website": 3, "end": "2015-11-21", "author": "Bryden Legg", "type": 1, "pledged": "0", "title": "Bryden Legg (Playlist Productions) Needs Gear. (no more renting)", "project_url": "https://www.rockethub.com/projects/56752-bryden-legg-playlist-productions-needs-gear-no-more-renting", "currency": "USD", "location": "Wetumpka, AL", "category_id": "12", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/56752/1430099177-large.jpg", "id": "56752"}
{"website": 3, "end": "2015-11-21", "author": "Bryden Legg", "type": 1, "pledged": "0", "title": "Bryden Legg (Playlist Productions) Needs Gear. (no more renting)", "project_url": "https://www.rockethub.com/projects/56752-bryden-legg-playlist-productions-needs-gear-no-more-renting", "currency": "USD", "location": "Wetumpka, AL", "category_id": "3", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/56752/1430099177-large.jpg", "id": "56752"}
{"website": 3, "end": "2015-11-21", "author": "Bryden Legg", "type": 1, "pledged": "0", "title": "Bryden Legg (Playlist Productions) Needs Gear. (no more renting)", "project_url": "https://www.rockethub.com/projects/56752-bryden-legg-playlist-productions-needs-gear-no-more-renting", "currency": "USD", "location": "Wetumpka, AL", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/56752/1430099177-large.jpg", "id": "56752"}
{"website": 3, "end": "2015-12-11", "author": "Vladislava Pliskach", "type": 1, "pledged": "0", "title": "Organization a concert Korean group", "project_url": "https://www.rockethub.com/projects/61403-organization-a-concert-korean-group", "currency": "USD", "location": "St. Petersburg, Russian Federation", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61403/1442064302-large.jpg", "id": "61403"}
{"website": 3, "end": "2015-12-11", "author": "Vladislava Pliskach", "type": 1, "pledged": "0", "title": "Organization a concert Korean group", "project_url": "https://www.rockethub.com/projects/61403-organization-a-concert-korean-group", "currency": "USD", "location": "St. Petersburg, Russian Federation", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61403/1442064302-large.jpg", "id": "61403"}
{"website": 3, "end": "2015-12-11", "author": "Vladislava Pliskach", "type": 1, "pledged": "0", "title": "Organization a concert Korean group", "project_url": "https://www.rockethub.com/projects/61403-organization-a-concert-korean-group", "currency": "USD", "location": "St. Petersburg, Russian Federation", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61403/1442064302-large.jpg", "id": "61403"}
{"website": 3, "end": "2015-12-11", "author": "Vladislava Pliskach", "type": 1, "pledged": "0", "title": "Organization a concert Korean group", "project_url": "https://www.rockethub.com/projects/61403-organization-a-concert-korean-group", "currency": "USD", "location": "St. Petersburg, Russian Federation", "category_id": "4", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61403/1442064302-large.jpg", "id": "61403"}
{"website": 3, "end": "2015-12-11", "author": "Vladislava Pliskach", "type": 1, "pledged": "0", "title": "Organization a concert Korean group", "project_url": "https://www.rockethub.com/projects/61403-organization-a-concert-korean-group", "currency": "USD", "location": "St. Petersburg, Russian Federation", "category_id": "14", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61403/1442064302-large.jpg", "id": "61403"}
{"website": 3, "end": "2015-12-11", "author": "Vladislava Pliskach", "type": 1, "pledged": "0", "title": "Organization a concert Korean group", "project_url": "https://www.rockethub.com/projects/61403-organization-a-concert-korean-group", "currency": "USD", "location": "St. Petersburg, Russian Federation", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61403/1442064302-large.jpg", "id": "61403"}
{"website": 3, "end": "2015-12-11", "author": "Vladislava Pliskach", "type": 1, "pledged": "0", "title": "Organization a concert Korean group", "project_url": "https://www.rockethub.com/projects/61403-organization-a-concert-korean-group", "currency": "USD", "location": "St. Petersburg, Russian Federation", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61403/1442064302-large.jpg", "id": "61403"}
{"website": 3, "end": "2015-10-30", "author": "Katie", "type": 1, "pledged": "0", "title": "Katie needs a video", "project_url": "https://www.rockethub.com/projects/61639-katie-needs-a-video", "currency": "USD", "location": "Tata, Hungary", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61639/1442832733-large.jpg", "id": "61639"}
{"website": 3, "end": "2015-12-01", "author": "Chris Rosenthal", "type": 1, "pledged": "0", "title": "Building a YouTube Gaming Channel", "project_url": "https://www.rockethub.com/projects/61002-building-a-youtube-gaming-channel", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61002/1441186664-large.jpg", "id": "61002"}
{"website": 3, "end": "2015-12-04", "author": "Vera", "type": 1, "pledged": "0", "title": "Support Lora go to a violin school", "project_url": "https://www.rockethub.com/projects/61159-support-lora-go-to-a-violin-school", "currency": "USD", "location": "Bulgaria", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61159/1441559336-large.JPG", "id": "61159"}
{"website": 3, "end": "2015-12-04", "author": "Vera", "type": 1, "pledged": "0", "title": "Support Lora go to a violin school", "project_url": "https://www.rockethub.com/projects/61159-support-lora-go-to-a-violin-school", "currency": "USD", "location": "Bulgaria", "category_id": "11", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61159/1441559336-large.JPG", "id": "61159"}
{"website": 3, "end": "2015-12-11", "author": "Vladislava Pliskach", "type": 1, "pledged": "0", "title": "Organization a concert Korean group", "project_url": "https://www.rockethub.com/projects/61403-organization-a-concert-korean-group", "currency": "USD", "location": "St. Petersburg, Russian Federation", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61403/1442064302-large.jpg", "id": "61403"}
{"website": 3, "end": "2015-12-01", "author": "Chris Rosenthal", "type": 1, "pledged": "0", "title": "Building a YouTube Gaming Channel", "project_url": "https://www.rockethub.com/projects/61002-building-a-youtube-gaming-channel", "currency": "USD", "location": "no location", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61002/1441186664-large.jpg", "id": "61002"}
{"website": 3, "end": "2015-12-01", "author": "Chris Rosenthal", "type": 1, "pledged": "0", "title": "Building a YouTube Gaming Channel", "project_url": "https://www.rockethub.com/projects/61002-building-a-youtube-gaming-channel", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61002/1441186664-large.jpg", "id": "61002"}
{"website": 3, "end": "2015-12-01", "author": "Chris Rosenthal", "type": 1, "pledged": "0", "title": "Building a YouTube Gaming Channel", "project_url": "https://www.rockethub.com/projects/61002-building-a-youtube-gaming-channel", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61002/1441186664-large.jpg", "id": "61002"}
{"website": 3, "end": "2015-12-01", "author": "Chris Rosenthal", "type": 1, "pledged": "0", "title": "Building a YouTube Gaming Channel", "project_url": "https://www.rockethub.com/projects/61002-building-a-youtube-gaming-channel", "currency": "USD", "location": "no location", "category_id": "12", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61002/1441186664-large.jpg", "id": "61002"}
{"website": 3, "end": "2015-12-01", "author": "Chris Rosenthal", "type": 1, "pledged": "0", "title": "Building a YouTube Gaming Channel", "project_url": "https://www.rockethub.com/projects/61002-building-a-youtube-gaming-channel", "currency": "USD", "location": "no location", "category_id": "3", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61002/1441186664-large.jpg", "id": "61002"}
{"website": 3, "end": "2015-12-01", "author": "Chris Rosenthal", "type": 1, "pledged": "0", "title": "Building a YouTube Gaming Channel", "project_url": "https://www.rockethub.com/projects/61002-building-a-youtube-gaming-channel", "currency": "USD", "location": "no location", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61002/1441186664-large.jpg", "id": "61002"}
{"website": 3, "end": "2015-11-21", "author": "Bryden Legg", "type": 1, "pledged": "0", "title": "Bryden Legg (Playlist Productions) Needs Gear. (no more renting)", "project_url": "https://www.rockethub.com/projects/56752-bryden-legg-playlist-productions-needs-gear-no-more-renting", "currency": "USD", "location": "Wetumpka, AL", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/56752/1430099177-large.jpg", "id": "56752"}
{"website": 3, "end": "2015-11-21", "author": "Bryden Legg", "type": 1, "pledged": "0", "title": "Bryden Legg (Playlist Productions) Needs Gear. (no more renting)", "project_url": "https://www.rockethub.com/projects/56752-bryden-legg-playlist-productions-needs-gear-no-more-renting", "currency": "USD", "location": "Wetumpka, AL", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/56752/1430099177-large.jpg", "id": "56752"}
{"website": 3, "end": "2015-11-21", "author": "Bryden Legg", "type": 1, "pledged": "0", "title": "Bryden Legg (Playlist Productions) Needs Gear. (no more renting)", "project_url": "https://www.rockethub.com/projects/56752-bryden-legg-playlist-productions-needs-gear-no-more-renting", "currency": "USD", "location": "Wetumpka, AL", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/56752/1430099177-large.jpg", "id": "56752"}
{"website": 3, "end": "2015-11-21", "author": "Bryden Legg", "type": 1, "pledged": "0", "title": "Bryden Legg (Playlist Productions) Needs Gear. (no more renting)", "project_url": "https://www.rockethub.com/projects/56752-bryden-legg-playlist-productions-needs-gear-no-more-renting", "currency": "USD", "location": "Wetumpka, AL", "category_id": "4", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/56752/1430099177-large.jpg", "id": "56752"}
{"website": 3, "end": "2015-11-21", "author": "Bryden Legg", "type": 1, "pledged": "0", "title": "Bryden Legg (Playlist Productions) Needs Gear. (no more renting)", "project_url": "https://www.rockethub.com/projects/56752-bryden-legg-playlist-productions-needs-gear-no-more-renting", "currency": "USD", "location": "Wetumpka, AL", "category_id": "14", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/56752/1430099177-large.jpg", "id": "56752"}
{"website": 3, "end": "2015-11-21", "author": "Bryden Legg", "type": 1, "pledged": "0", "title": "Bryden Legg (Playlist Productions) Needs Gear. (no more renting)", "project_url": "https://www.rockethub.com/projects/56752-bryden-legg-playlist-productions-needs-gear-no-more-renting", "currency": "USD", "location": "Wetumpka, AL", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/56752/1430099177-large.jpg", "id": "56752"}
{"website": 3, "end": "2015-11-21", "author": "Bryden Legg", "type": 1, "pledged": "0", "title": "Bryden Legg (Playlist Productions) Needs Gear. (no more renting)", "project_url": "https://www.rockethub.com/projects/56752-bryden-legg-playlist-productions-needs-gear-no-more-renting", "currency": "USD", "location": "Wetumpka, AL", "category_id": "1", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/56752/1430099177-large.jpg", "id": "56752"}
