{"end": "12days", "title": "Green Boat Men Fund", "author": "By Munro Driessen", "project_url": "https://www.rockethub.com/projects/58707-green-boat-men-fund", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58707/1434849122-large.JPG", "id": "58707"}
{"end": "19days", "title": "International goat\u2019s milk mega farm CAPELLA", "author": "By Evgeny Durin", "project_url": "https://www.rockethub.com/projects/59547-international-goat-s-milk-mega-farm-capella", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59547/1436970022-large.jpg", "id": "59547"}
{"end": "3days", "title": "French Pastry Campus in ENSP", "author": "By Tanya Pushkina", "project_url": "https://www.rockethub.com/projects/56377-french-pastry-campus-in-ensp", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/56377/1429377421-large.jpg", "id": "56377"}
{"end": "44days", "title": "Sugar Free The Movie- Break The Addiction", "author": "By Sugar Free The Movie", "project_url": "https://www.rockethub.com/projects/57823-sugar-free-the-movie-break-the-addiction", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/57823/1436497057-large.jpg", "id": "57823"}
{"end": "81days", "title": "Smart Poultry Farming, (layer chickens for best quality eggs production).", "author": "By Emmanuel Chiduo", "project_url": "https://www.rockethub.com/projects/60653-smart-poultry-farming-layer-chickens-for-best-quality-eggs-production", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60653/1440258226-large.jpg", "id": "60653"}
{"end": "5days", "title": "IceCreamZilla\u00ae: 24/7 Global \"On-Demand\" Ice Cream Delivery", "author": "By Simon Angelov", "project_url": "https://www.rockethub.com/projects/58271-icecreamzilla-24-7-global-on-demand-ice-cream-delivery", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58271/1433818217-large.jpg", "id": "58271"}
{"end": "21days", "title": "Help fund my postgraduate studies and learn about athletes diet and health", "author": "By Lorna Doyle", "project_url": "https://www.rockethub.com/projects/58844-help-fund-my-postgraduate-studies-and-learn-about-athletes-diet-and-health", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58844/1435315703-large.jpg", "id": "58844"}
{"end": "8days", "title": "Homeless Old Disabled Woman In Danger Need A Camper", "author": "By Loveable Atsixty", "project_url": "https://www.rockethub.com/projects/58098-homeless-old-disabled-woman-in-danger-need-a-camper", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58098/1433383355-large.jpg", "id": "58098"}
{"end": "7days", "title": "Wildhoneybush", "author": "By Jaques Bester", "project_url": "https://www.rockethub.com/projects/57872-wildhoneybush", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/57872/1433941739-large.jpg", "id": "57872"}
