{"website": 3, "end": "2015-12-09", "author": "Wayde Fishman", "type": 1, "pledged": "2950", "title": "PRICE FOR PARADISE -The Struggles & Successes of living the Real Hawaii", "project_url": "https://www.rockethub.com/projects/58805-price-for-paradise-the-struggles-successes-of-living-the-real-hawaii", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58805/1435718773-large.jpg", "id": "58805"}
{"website": 3, "end": "2015-12-04", "author": "Phillip Elkins", "type": 1, "pledged": "175", "title": "Popcorn Movie Box", "project_url": "https://www.rockethub.com/projects/61136-popcorn-movie-box", "currency": "USD", "location": "Tucson, AZ", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61136/1441483814-large.png", "id": "61136"}
{"website": 3, "end": "2015-10-28", "author": "Jeff Jaynes", "type": 1, "pledged": "0", "title": "Travel Show", "project_url": "https://www.rockethub.com/projects/59966-travel-show", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59966/1438281832-large.jpg", "id": "59966"}
{"website": 3, "end": "2015-10-15", "author": "Mandy Kalish", "type": 1, "pledged": "955", "title": "Help Launch TreasureMatching.com!", "project_url": "https://www.rockethub.com/projects/61154-help-launch-treasurematching-com", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61154/1441556366-large.jpg", "id": "61154"}
{"website": 3, "end": "2015-12-04", "author": "Von-Anise McCoy", "type": 1, "pledged": "40", "title": "Bougie Betty", "project_url": "https://www.rockethub.com/projects/60732-bougie-betty", "currency": "USD", "location": "New York , NY", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60732/1443728809-large.JPG", "id": "60732"}
{"website": 3, "end": "2015-11-19", "author": "Christina", "type": 1, "pledged": "0", "title": "Support Daughter for Hollywood Showcase in LA", "project_url": "https://www.rockethub.com/projects/60631-support-daughter-for-hollywood-showcase-in-la", "currency": "USD", "location": "Shasta Lake City, CA", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60631/1440181269-large.jpg", "id": "60631"}
{"website": 3, "end": "2015-10-26", "author": "Anganile Thomson Mwakyanjala", "type": 1, "pledged": "350", "title": "Media for youth inclusion in a democratic Tanzania", "project_url": "https://www.rockethub.com/projects/59906-media-for-youth-inclusion-in-a-democratic-tanzania", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59906/1438112364-large.jpg", "id": "59906"}
{"website": 3, "end": "2015-10-26", "author": "Pablo Gracia", "type": 1, "pledged": "0", "title": "help the future of cinematography , film making and music production", "project_url": "https://www.rockethub.com/projects/59905-help-the-future-of-cinematography-film-making-and-music-production", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59905/1438104815-large.jpg", "id": "59905"}
{"website": 3, "end": "2015-10-22", "author": "Russell Rope", "type": 1, "pledged": "0", "title": "RR Productions @RussellRope .com", "project_url": "https://www.rockethub.com/projects/60684-rr-productions-russellrope-com", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60684/1440354273-large.jpg", "id": "60684"}
