{"website": 3, "end": "2015-10-15", "author": "Sugar Free The Movie", "type": 1, "pledged": "1191", "title": "Sugar Free The Movie- Break The Addiction", "project_url": "https://www.rockethub.com/projects/57823-sugar-free-the-movie-break-the-addiction", "currency": "USD", "location": "no location", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/57823/1436497057-large.jpg", "id": "57823"}
{"website": 3, "end": "2015-10-29", "author": "Tina Klein", "type": 1, "pledged": "0", "title": "Super Coupon Woman's 2015 $50,000 Donation Challenge!", "project_url": "https://www.rockethub.com/projects/59560-super-coupon-woman-s-2015-50-000-donation-challenge", "currency": "USD", "location": "Wylie, TX", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59560/1436997233-large.jpg", "id": "59560"}
{"website": 3, "end": "2015-10-28", "author": "Brandy Gregory", "type": 1, "pledged": "0", "title": "Farms for the Future", "project_url": "https://www.rockethub.com/projects/59958-farms-for-the-future", "currency": "USD", "location": "no location", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59958/1438271613-large.jpg", "id": "59958"}
{"website": 3, "end": "2015-11-21", "author": "Emmanuel Chiduo", "type": 1, "pledged": "100", "title": "Smart Poultry Farming, (layer chickens for best quality eggs production).", "project_url": "https://www.rockethub.com/projects/60653-smart-poultry-farming-layer-chickens-for-best-quality-eggs-production", "currency": "USD", "location": "Morogoro, Tanzania, United Republic of", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60653/1440258226-large.jpg", "id": "60653"}
{"website": 3, "end": "2015-10-20", "author": "Chad Fields", "type": 1, "pledged": "0", "title": "Development of Personal Smart Blender and App that Weighs Contents!!", "project_url": "https://www.rockethub.com/projects/59743-development-of-personal-smart-blender-and-app-that-weighs-contents", "currency": "USD", "location": "Duncanville, TX", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59743/1437595483-large.jpg", "id": "59743"}
{"website": 3, "end": "2015-10-29", "author": "Tamika Tillis", "type": 1, "pledged": "0", "title": "$5 Challenge to house homeless", "project_url": "https://www.rockethub.com/projects/60011-5-challenge-to-house-homeless", "currency": "USD", "location": "Sacramento , Ca", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60011/1438389869-large.jpg", "id": "60011"}
{"website": 3, "end": "2015-11-10", "author": "Nancy Zapata Faella", "type": 1, "pledged": "245", "title": "My Coffee Cubes", "project_url": "https://www.rockethub.com/projects/61465-my-coffee-cubes", "currency": "USD", "location": "Johnston, RI", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61465/1443327424-large.jpg", "id": "61465"}
{"website": 3, "end": "2015-10-24", "author": "Tommi Linn Livingston", "type": 1, "pledged": "0", "title": "Support for Resturant Business - Saucy Witch", "project_url": "https://www.rockethub.com/projects/59850-support-for-resturant-business-saucy-witch", "currency": "USD", "location": "Salem, MA", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59850/1437951742-large.", "id": "59850"}
{"website": 3, "end": "2015-10-30", "author": "Brendan smith", "type": 1, "pledged": "0", "title": "Saving shelter pets", "project_url": "https://www.rockethub.com/projects/60031-saving-shelter-pets", "currency": "USD", "location": "Rocky point, NY", "category_id": "8", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60031/1438460753-large.jpg", "id": "60031"}
