{"website": 3, "end": "2015-11-18", "author": "Ted Forbes", "type": 1, "pledged": "8575", "title": "Support The Art of Photography Artist Series!", "project_url": "https://www.rockethub.com/projects/61988-support-the-art-of-photography-artist-series", "currency": "USD", "location": "Dallas, TX", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61988/1445025204-large.jpg", "id": "61988"}
{"website": 3, "end": "2015-11-18", "author": "Alicia Hansen", "type": 1, "pledged": "1585", "title": "NYC SALT: Buy a Camera, Equip a Kid, Change a Life Forever!", "project_url": "https://www.rockethub.com/projects/61964-nyc-salt-buy-a-camera-equip-a-kid-change-a-life-forever", "currency": "USD", "location": "New York, NY", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61964/1445288559-large.jpg", "id": "61964"}
{"website": 3, "end": "2015-10-25", "author": "Eleonore Nitzschke", "type": 1, "pledged": "5", "title": "The spiral of adventure", "project_url": "https://www.rockethub.com/projects/59779-the-spiral-of-adventure", "currency": "USD", "location": "New York City , NY", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59779/1437681001-large.JPG", "id": "59779"}
{"website": 3, "end": "2015-11-18", "author": "Street Ballet", "type": 1, "pledged": "1650", "title": "Street Ballet Video", "project_url": "https://www.rockethub.com/projects/61412-street-ballet-video", "currency": "USD", "location": "no location", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61412/1445118693-large.jpg", "id": "61412"}
{"website": 3, "end": "2015-11-15", "author": "Sharon Tan", "type": 1, "pledged": "2680", "title": "Support Elastic Magazine's Launch Issue!", "project_url": "https://www.rockethub.com/projects/62120-support-elastic-magazine-s-launch-issue", "currency": "USD", "location": "no location", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/62120/1444363017-large.png", "id": "62120"}
{"website": 3, "end": "2015-11-05", "author": "Lea Lee", "type": 1, "pledged": "0", "title": "Dreams That Money Can Buy", "project_url": "https://www.rockethub.com/projects/59829-dreams-that-money-can-buy", "currency": "USD", "location": "New York City , Ny", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59829/1437865538-large.jpg", "id": "59829"}
{"website": 3, "end": "2015-11-18", "author": "Hank Vohrer", "type": 1, "pledged": "755", "title": "PARALLUX: 3D Art Series for the View-Master!", "project_url": "https://www.rockethub.com/projects/61359-parallux-3d-art-series-for-the-view-master", "currency": "USD", "location": "Baltimore, MD", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61359/1443291253-large.jpg", "id": "61359"}
{"website": 3, "end": "2015-11-24", "author": "Elizabeth Neilson", "type": 1, "pledged": "45", "title": "Inner City School Arts Enrichment", "project_url": "https://www.rockethub.com/projects/62389-inner-city-school-arts-enrichment", "currency": "USD", "location": "Minneapolis, MN", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/62389/1444880147-large.jpg", "id": "62389"}
{"website": 3, "end": "2015-11-12", "author": "Phill Johnston", "type": 1, "pledged": "0", "title": "Boat Fund", "project_url": "https://www.rockethub.com/projects/59848-boat-fund", "currency": "USD", "location": "San jose, CA", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59848/1437948633-large.jpg", "id": "59848"}
