{"end": "35days", "title": "Floating Opera New York Pelleas and Melisande", "author": "By Isabel Milenski", "project_url": "https://www.rockethub.com/projects/60540-floating-opera-new-york-pelleas-and-melisande", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60540/1439865071-large.png", "id": "60540"}
{"end": "14days", "title": "Tunes & Tails: Spread the Love Fundraising Event!", "author": "By Ashley Grant", "project_url": "https://www.rockethub.com/projects/60393-tunes-tails-spread-the-love-fundraising-event", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60393/1439481183-large.jpg", "id": "60393"}
{"end": "12days", "title": "'Your Call...' by Kevin Jones, World Premiere in London", "author": "By Kevin Jones", "project_url": "https://www.rockethub.com/projects/58720-your-call-by-kevin-jones-world-premiere-in-london", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58720/1434904402-large.jpg", "id": "58720"}
{"end": "3days", "title": "Getting the Show on the Road: Art for Everyone", "author": "By Samantha Eden", "project_url": "https://www.rockethub.com/projects/60555-getting-the-show-on-the-road-art-for-everyone", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60555/1439908384-large.jpg", "id": "60555"}
{"end": "41days", "title": "The Tip Jar - Fill Frances Drost's Musical Tip Jar in 2015", "author": "By Frances Drost", "project_url": "https://www.rockethub.com/projects/60711-the-tip-jar-fill-frances-drost-s-musical-tip-jar-in-2015", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60711/1440436045-large.jpg", "id": "60711"}
{"end": "57days", "title": "Naomi Striemer Album 2016!!", "author": "By Naomi Striemer", "project_url": "https://www.rockethub.com/projects/59968-naomi-striemer-album-2016", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59968/1438281789-large.jpg", "id": "59968"}
{"end": "6days", "title": "Abracadabra: A Cuban Fantasy", "author": "By Oriente Lopez", "project_url": "https://www.rockethub.com/projects/59590-abracadabra-a-cuban-fantasy", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59590/1437076021-large.jpg", "id": "59590"}
{"end": "60days", "title": "KidWorks Avanti Music Program", "author": "By Joe Cristina", "project_url": "https://www.rockethub.com/projects/59922-kidworks-avanti-music-program", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59922/1439076763-large.png", "id": "59922"}
{"end": "76days", "title": "9th Phoenix Mobile DJ Service", "author": "By Deven Balsam", "project_url": "https://www.rockethub.com/projects/60539-9th-phoenix-mobile-dj-service", "location": "", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60539/1439918632-large.jpg", "id": "60539"}
