{"website": 3, "end": "2015-10-17", "author": "Shirin Tinati", "type": 1, "pledged": "13355", "title": "\"I Am Warrior\" a Photo Book to Empower Women During Breast Cancer Treatment", "project_url": "https://www.rockethub.com/projects/60987-i-am-warrior-a-photo-book-to-empower-women-during-breast-cancer-treatment", "currency": "USD", "location": "no location", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60987/1444154811-large.png", "id": "60987"}
{"website": 3, "end": "2015-10-31", "author": "Brad L. Baird", "type": 1, "pledged": "35", "title": "\"Fred's Story\" - Family Hospitals & Senior Centres Book Placement Program", "project_url": "https://www.rockethub.com/projects/61531-fred-s-story-family-hospitals-senior-centres-book-placement-program", "currency": "USD", "location": "Edmonton, Canada", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61531/1442486052-large.jpg", "id": "61531"}
{"website": 3, "end": "2015-12-09", "author": "Wayde Fishman", "type": 1, "pledged": "3070", "title": "PRICE FOR PARADISE -The Struggles & Successes of living the Real Hawaii", "project_url": "https://www.rockethub.com/projects/58805-price-for-paradise-the-struggles-successes-of-living-the-real-hawaii", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58805/1435718773-large.jpg", "id": "58805"}
{"website": 3, "end": "2015-10-17", "author": "Shirin Tinati", "type": 1, "pledged": "13355", "title": "\"I Am Warrior\" a Photo Book to Empower Women During Breast Cancer Treatment", "project_url": "https://www.rockethub.com/projects/60987-i-am-warrior-a-photo-book-to-empower-women-during-breast-cancer-treatment", "currency": "USD", "location": "no location", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60987/1444154811-large.png", "id": "60987"}
{"website": 3, "end": "2015-12-31", "author": "Nasya Kamrat", "type": 1, "pledged": "6616", "title": "UNSPEAKABLE: An Animated Holocaust Documentary", "project_url": "https://www.rockethub.com/projects/43758-unspeakable-an-animated-holocaust-documentary", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/43758/1401759333-large.jpg", "id": "43758"}
{"website": 3, "end": "2015-11-20", "author": "Steve Thornton", "type": 1, "pledged": "200", "title": "Help Stephen attend AND's November Per4mance Intensive Workshop", "project_url": "https://www.rockethub.com/projects/61621-help-stephen-attend-and-s-november-per4mance-intensive-workshop", "currency": "USD", "location": "Brooklyn, NY", "category_id": "12", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61621/1442776516-large.jpg", "id": "61621"}
{"website": 3, "end": "2015-10-20", "author": "Shako Khiski", "type": 1, "pledged": "3885", "title": "Help Shako Raise $3000 in 30 Days For His EP!", "project_url": "https://www.rockethub.com/projects/60660-help-shako-raise-3000-in-30-days-for-his-ep", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60660/1442533702-large.jpg", "id": "60660"}
{"website": 3, "end": "2015-11-09", "author": "Wyrd Theatre", "type": 1, "pledged": "1405", "title": "Support Wyrd Theatre's \"Tartuffe en Burlesque!\"", "project_url": "https://www.rockethub.com/projects/61413-support-wyrd-theatre-s-tartuffe-en-burlesque", "currency": "USD", "location": "no location", "category_id": "3", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61413/1444276531-large.jpg", "id": "61413"}
{"website": 3, "end": "2015-10-20", "author": "Shako Khiski", "type": 1, "pledged": "3885", "title": "Help Shako Raise $3000 in 30 Days For His EP!", "project_url": "https://www.rockethub.com/projects/60660-help-shako-raise-3000-in-30-days-for-his-ep", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60660/1442533702-large.jpg", "id": "60660"}
{"website": 3, "end": "2015-10-31", "author": "Joe Cristina", "type": 1, "pledged": "315", "title": "KidWorks Avanti Music Program", "project_url": "https://www.rockethub.com/projects/59922-kidworks-avanti-music-program", "currency": "USD", "location": "no location", "category_id": "13", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59922/1439076763-large.png", "id": "59922"}
{"website": 3, "end": "2015-11-06", "author": "Fred Sauter", "type": 1, "pledged": "5370", "title": "Fund Astronaut Love Show -a new musical by Leschen & Sauter (Bedbugs!!!)", "project_url": "https://www.rockethub.com/projects/61801-fund-astronaut-love-show-a-new-musical-by-leschen-sauter-bedbugs", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61801/1444588774-large.gif", "id": "61801"}
{"website": 3, "end": "2015-11-06", "author": "Fred Sauter", "type": 1, "pledged": "5370", "title": "Fund Astronaut Love Show -a new musical by Leschen & Sauter (Bedbugs!!!)", "project_url": "https://www.rockethub.com/projects/61801-fund-astronaut-love-show-a-new-musical-by-leschen-sauter-bedbugs", "currency": "USD", "location": "no location", "category_id": "9", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61801/1444588774-large.gif", "id": "61801"}
{"website": 3, "end": "2015-11-06", "author": "Fred Sauter", "type": 1, "pledged": "5370", "title": "Fund Astronaut Love Show -a new musical by Leschen & Sauter (Bedbugs!!!)", "project_url": "https://www.rockethub.com/projects/61801-fund-astronaut-love-show-a-new-musical-by-leschen-sauter-bedbugs", "currency": "USD", "location": "no location", "category_id": "10", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61801/1444588774-large.gif", "id": "61801"}
{"website": 3, "end": "2015-11-06", "author": "Fred Sauter", "type": 1, "pledged": "5370", "title": "Fund Astronaut Love Show -a new musical by Leschen & Sauter (Bedbugs!!!)", "project_url": "https://www.rockethub.com/projects/61801-fund-astronaut-love-show-a-new-musical-by-leschen-sauter-bedbugs", "currency": "USD", "location": "no location", "category_id": "12", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61801/1444588774-large.gif", "id": "61801"}
{"website": 3, "end": "2015-11-06", "author": "Fred Sauter", "type": 1, "pledged": "5370", "title": "Fund Astronaut Love Show -a new musical by Leschen & Sauter (Bedbugs!!!)", "project_url": "https://www.rockethub.com/projects/61801-fund-astronaut-love-show-a-new-musical-by-leschen-sauter-bedbugs", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61801/1444588774-large.gif", "id": "61801"}
{"website": 3, "end": "2015-11-06", "author": "Fred Sauter", "type": 1, "pledged": "5370", "title": "Fund Astronaut Love Show -a new musical by Leschen & Sauter (Bedbugs!!!)", "project_url": "https://www.rockethub.com/projects/61801-fund-astronaut-love-show-a-new-musical-by-leschen-sauter-bedbugs", "currency": "USD", "location": "no location", "category_id": "3", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61801/1444588774-large.gif", "id": "61801"}
{"website": 3, "end": "2015-11-06", "author": "Fred Sauter", "type": 1, "pledged": "5370", "title": "Fund Astronaut Love Show -a new musical by Leschen & Sauter (Bedbugs!!!)", "project_url": "https://www.rockethub.com/projects/61801-fund-astronaut-love-show-a-new-musical-by-leschen-sauter-bedbugs", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61801/1444588774-large.gif", "id": "61801"}
{"website": 3, "end": "2015-11-08", "author": "Scott Ambrose", "type": 1, "pledged": "130", "title": "The Sincerity Lodge Charity Christmas Tree for Kennedy Krieger Festival", "project_url": "https://www.rockethub.com/projects/61989-the-sincerity-lodge-charity-christmas-tree-for-kennedy-krieger-festival", "currency": "USD", "location": "Baltimore, MD", "category_id": "4", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61989/1444443463-large.jpg", "id": "61989"}
