{"website": 3, "end": "2015-11-18", "author": "Allison Veltz", "type": 1, "pledged": "7776", "title": "I want to make The White Room EP with you.", "project_url": "https://www.rockethub.com/projects/61452-i-want-to-make-the-white-room-ep-with-you", "currency": "USD", "location": "Nashville, TN", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61452/1445261025-large.jpg", "id": "61452"}
{"website": 3, "end": "2015-11-18", "author": "Tim Cluff", "type": 1, "pledged": "4890", "title": "Orphan Jane: The Musical!", "project_url": "https://www.rockethub.com/projects/61269-orphan-jane-the-musical", "currency": "USD", "location": "Brooklyn, NY", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61269/1442323446-large.jpg", "id": "61269"}
{"website": 3, "end": "2015-11-18", "author": "Heather Jacks", "type": 1, "pledged": "2796", "title": "Busk Loose: 30 Buskers, 1 Song, 1 Day, 1 Take", "project_url": "https://www.rockethub.com/projects/60945-busk-loose-30-buskers-1-song-1-day-1-take", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60945/1443368541-large.jpg", "id": "60945"}
{"website": 3, "end": "2015-11-18", "author": "Dani Mari", "type": 1, "pledged": "5305", "title": "Help Female Frequency make an album created entirely by women!", "project_url": "https://www.rockethub.com/projects/60849-help-female-frequency-make-an-album-created-entirely-by-women", "currency": "USD", "location": "Brooklyn, NY", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60849/1442811304-large.jpg", "id": "60849"}
{"website": 3, "end": "2015-11-18", "author": "Steev Richter", "type": 1, "pledged": "2440", "title": "Help Fund Steev Richter's New Album, \"Beloved\"", "project_url": "https://www.rockethub.com/projects/61696-help-fund-steev-richter-s-new-album-beloved", "currency": "USD", "location": "Nyack, NY", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61696/1442943020-large.jpg", "id": "61696"}
{"website": 3, "end": "2015-11-18", "author": "Allison Veltz", "type": 1, "pledged": "7776", "title": "I want to make The White Room EP with you.", "project_url": "https://www.rockethub.com/projects/61452-i-want-to-make-the-white-room-ep-with-you", "currency": "USD", "location": "Nashville, TN", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61452/1445261025-large.jpg", "id": "61452"}
{"website": 3, "end": "2015-11-18", "author": "Allison", "type": 1, "pledged": "1975", "title": "Support \"The Legacy of Daisy Dean\" Theatre Project by Allison Guinn", "project_url": "https://www.rockethub.com/projects/61234-support-the-legacy-of-daisy-dean-theatre-project-by-allison-guinn", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61234/1441735931-large.jpeg", "id": "61234"}
{"website": 3, "end": "2015-11-18", "author": "Tim Cluff", "type": 1, "pledged": "4890", "title": "Orphan Jane: The Musical!", "project_url": "https://www.rockethub.com/projects/61269-orphan-jane-the-musical", "currency": "USD", "location": "Brooklyn, NY", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61269/1442323446-large.jpg", "id": "61269"}
{"website": 3, "end": "2015-11-30", "author": "Grace B Lunsford", "type": 1, "pledged": "13390", "title": "Grace and Corbett 2016 Tour- Proof is Possible!", "project_url": "https://www.rockethub.com/projects/62383-grace-and-corbett-2016-tour-proof-is-possible", "currency": "USD", "location": "Valrico, FL", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/62383/1444848330-large.jpg", "id": "62383"}
{"website": 3, "end": "2015-11-18", "author": "Heather Jacks", "type": 1, "pledged": "2796", "title": "Busk Loose: 30 Buskers, 1 Song, 1 Day, 1 Take", "project_url": "https://www.rockethub.com/projects/60945-busk-loose-30-buskers-1-song-1-day-1-take", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60945/1443368541-large.jpg", "id": "60945"}
{"website": 3, "end": "2015-11-18", "author": "Lesley Barth", "type": 1, "pledged": "2660", "title": "Lesley Barth's First Full-Length Album!", "project_url": "https://www.rockethub.com/projects/61408-lesley-barth-s-first-full-length-album", "currency": "USD", "location": "no location", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61408/1442082563-large.jpg", "id": "61408"}
{"website": 3, "end": "2015-11-18", "author": "Dani Mari", "type": 1, "pledged": "5305", "title": "Help Female Frequency make an album created entirely by women!", "project_url": "https://www.rockethub.com/projects/60849-help-female-frequency-make-an-album-created-entirely-by-women", "currency": "USD", "location": "Brooklyn, NY", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60849/1442811304-large.jpg", "id": "60849"}
{"website": 3, "end": "2015-11-18", "author": "Marc-Andre Seguin", "type": 1, "pledged": "835", "title": "JazzGuitarLessons.net's \"REAL Teacher\" Records an Album - Marc-Andre Seguin", "project_url": "https://www.rockethub.com/projects/61278-jazzguitarlessons-net-s-real-teacher-records-an-album-marc-andre-seguin", "currency": "USD", "location": "Gatineau, Canada", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61278/1441917615-large.jpg", "id": "61278"}
{"website": 3, "end": "2015-11-18", "author": "Steev Richter", "type": 1, "pledged": "2440", "title": "Help Fund Steev Richter's New Album, \"Beloved\"", "project_url": "https://www.rockethub.com/projects/61696-help-fund-steev-richter-s-new-album-beloved", "currency": "USD", "location": "Nyack, NY", "category_id": "6", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61696/1442943020-large.jpg", "id": "61696"}
