{"website": 3, "end": "2015-11-18", "author": "Alex Woodward", "type": 1, "pledged": "1190", "title": "Dance Around The Globe - An exciting adventure", "project_url": "https://www.rockethub.com/projects/61271-dance-around-the-globe-an-exciting-adventure", "currency": "USD", "location": "Chicago, IL", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61271/1441807525-large.jpg", "id": "61271"}
{"website": 3, "end": "2015-11-12", "author": "Wayne Fernandes", "type": 1, "pledged": "525", "title": "Zing Airlines", "project_url": "https://www.rockethub.com/projects/61446-zing-airlines", "currency": "USD", "location": "no location", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61446/1444358852-large.png", "id": "61446"}
{"website": 3, "end": "2015-10-30", "author": "Ruta", "type": 1, "pledged": "0", "title": "Creating an off-grid place where everyone is welcome (peace, love, harmony)", "project_url": "https://www.rockethub.com/projects/60016-creating-an-off-grid-place-where-everyone-is-welcome-peace-love-harmony", "currency": "USD", "location": "no location", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60016/1438411729-large.jpg", "id": "60016"}
{"website": 3, "end": "2015-11-18", "author": "Candice Waltrip", "type": 1, "pledged": "127", "title": "TRAVEL POCKETS- Sisters who have a passion for travel & style.", "project_url": "https://www.rockethub.com/projects/61877-travel-pockets-sisters-who-have-a-passion-for-travel-style", "currency": "USD", "location": "no location", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61877/1444418621-large.jpg", "id": "61877"}
{"website": 3, "end": "2015-11-12", "author": "Tommi Linn Livingston", "type": 1, "pledged": "0", "title": "Support for Resturant Business - Saucy Witch", "project_url": "https://www.rockethub.com/projects/59850-support-for-resturant-business-saucy-witch", "currency": "USD", "location": "Salem, MA", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59850/1437951742-large.", "id": "59850"}
{"website": 3, "end": "2015-11-13", "author": "Andrey Tarasov", "type": 1, "pledged": "0", "title": "Ekaterinburg Hostel", "project_url": "https://www.rockethub.com/projects/60438-ekaterinburg-hostel", "currency": "USD", "location": "Ekaterinburg, Russian Federation", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/60438/1439633700-large.jpg", "id": "60438"}
{"website": 3, "end": "2015-12-09", "author": "Wayde Fishman", "type": 1, "pledged": "3140", "title": "PRICE FOR PARADISE -The Struggles & Successes of living the Real Hawaii", "project_url": "https://www.rockethub.com/projects/58805-price-for-paradise-the-struggles-successes-of-living-the-real-hawaii", "currency": "USD", "location": "no location", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/58805/1435718773-large.jpg", "id": "58805"}
{"website": 3, "end": "2015-10-28", "author": "Jeff Jaynes", "type": 1, "pledged": "0", "title": "Travel Show", "project_url": "https://www.rockethub.com/projects/59966-travel-show", "currency": "USD", "location": "no location", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/59966/1438281832-large.jpg", "id": "59966"}
{"website": 3, "end": "2015-11-09", "author": "Madhawa Habarakada", "type": 1, "pledged": "0", "title": "Photography Exploration Tour and Camera Equipment", "project_url": "https://www.rockethub.com/projects/61004-photography-exploration-tour-and-camera-equipment", "currency": "USD", "location": "no location", "category_id": "15", "img_url": "https://rockethub-images-production.s3.amazonaws.com/images/61004/1441187935-large.jpg", "id": "61004"}
