{"website": 2, "end": "2015-12-12", "title": "Iqaluit Humane Society: Making Strides", "type": 1, "pledged": "1494", "author": "Heather Crowley", "project_url": "https://www.indiegogo.com/projects/iqaluit-humane-society-making-strides/pinw?sa=0&sp=0", "currency": "CAD", "location": "Canada Iqaluit, Nunavut", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444665248/ioy9ziiddmdz2xmrh2oh.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-07", "title": "AVIARY FOR RESCUED BIRDS", "type": 1, "pledged": "627", "author": "marcel.woolfe", "project_url": "https://www.indiegogo.com/projects/aviary-for-rescued-birds/pipp?sa=0&sp=0", "currency": "AUD", "location": "Australia Newcastle", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444282934/r33us0b7zc7r9ifr5m2y.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-13", "title": "Sleepless in Seattle 2015 - Seattle Gives Back", "type": 1, "pledged": "8090", "author": "Eddie Wang", "project_url": "https://www.indiegogo.com/projects/sleepless-in-seattle-2015-seattle-gives-back--2/pinw?sa=0&sp=0", "currency": "USD", "location": "United States Seattle, Washington", "category_id": "14", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1443895682/fz7pu0sry0ur3rxucprs.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-12", "title": "Support for the amazing team of performers & DJs", "type": 1, "pledged": "0", "author": "Majestic Meadow-Gathering", "project_url": "https://www.indiegogo.com/projects/support-for-the-amazing-team-of-performers-djs/pinw?sa=0&sp=0", "currency": "USD", "location": "Canada Lawrence Lake, Alberta", "category_id": "3", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444677941/oir4fkdbzpssbfxzfpwm.png", "id": "use title"}
{"website": 2, "end": "2015-12-12", "title": "National Museum of American Religion", "type": 1, "pledged": "2313", "author": "Colleen Prior", "project_url": "https://www.indiegogo.com/projects/national-museum-of-american-religion/pinw?sa=0&sp=0", "currency": "USD", "location": "United States Washington, District of Columbia", "category_id": "13", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444615576/vt5jpqmeouxh6zovyq4y.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-17", "title": "UTHERMIC Coldscreen Lotion", "type": 1, "pledged": "3625", "author": "U\u02daThermic", "project_url": "https://www.indiegogo.com/projects/uthermic-coldscreen-lotion/pinw?sa=0&sp=0", "currency": "USD", "location": "United States Boulder, Colorado", "category_id": "4", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444677499/uh49dqt8mjcepnmgnahv.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-13", "title": "Legal Fees", "type": 1, "pledged": "720", "author": "Eleni Vlachos", "project_url": "https://www.indiegogo.com/projects/legal-fees--30/pinw?sa=0&sp=0", "currency": "USD", "location": "United States Seattle, Washington", "category_id": "1", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444196412/uhf2tllgqhzymnpzjamp.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-13", "title": "Legal Fees", "type": 1, "pledged": "720", "author": "Eleni Vlachos", "project_url": "https://www.indiegogo.com/projects/legal-fees--30/pipp?sa=0&sp=0", "currency": "USD", "location": "United States Seattle, Washington", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444196412/uhf2tllgqhzymnpzjamp.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-15", "title": "The First Mural for Asian American Women Artists", "type": 1, "pledged": "2103", "author": "Asian American Women Artists Association (AAWAA)", "project_url": "https://www.indiegogo.com/projects/the-first-mural-for-asian-american-women-artists/pipp?sa=0&sp=0", "currency": "USD", "location": "United States San Francisco, California", "category_id": "14", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1443558280/oxugdbhpyxc965z5um4y.png", "id": "use title"}
{"website": 2, "end": "2015-11-15", "title": "The First Mural for Asian American Women Artists", "type": 1, "pledged": "2103", "author": "Asian American Women Artists Association (AAWAA)", "project_url": "https://www.indiegogo.com/projects/the-first-mural-for-asian-american-women-artists/pipp?sa=0&sp=0", "currency": "USD", "location": "United States San Francisco, California", "category_id": "3", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1443558280/oxugdbhpyxc965z5um4y.png", "id": "use title"}
{"website": 2, "end": "2015-11-15", "title": "The First Mural for Asian American Women Artists", "type": 1, "pledged": "2103", "author": "Asian American Women Artists Association (AAWAA)", "project_url": "https://www.indiegogo.com/projects/the-first-mural-for-asian-american-women-artists/pipp?sa=0&sp=0", "currency": "USD", "location": "United States San Francisco, California", "category_id": "13", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1443558280/oxugdbhpyxc965z5um4y.png", "id": "use title"}
{"website": 2, "end": "2015-11-15", "title": "The First Mural for Asian American Women Artists", "type": 1, "pledged": "2103", "author": "Asian American Women Artists Association (AAWAA)", "project_url": "https://www.indiegogo.com/projects/the-first-mural-for-asian-american-women-artists/pipp?sa=0&sp=0", "currency": "USD", "location": "United States San Francisco, California", "category_id": "4", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1443558280/oxugdbhpyxc965z5um4y.png", "id": "use title"}
{"website": 2, "end": "2015-11-15", "title": "The First Mural for Asian American Women Artists", "type": 1, "pledged": "2103", "author": "Asian American Women Artists Association (AAWAA)", "project_url": "https://www.indiegogo.com/projects/the-first-mural-for-asian-american-women-artists/pipp?sa=0&sp=0", "currency": "USD", "location": "United States San Francisco, California", "category_id": "1", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1443558280/oxugdbhpyxc965z5um4y.png", "id": "use title"}
{"website": 2, "end": "2015-12-12", "title": "Iqaluit Humane Society: Making Strides", "type": 1, "pledged": "1494", "author": "Heather Crowley", "project_url": "https://www.indiegogo.com/projects/iqaluit-humane-society-making-strides/pinw?sa=0&sp=0", "currency": "CAD", "location": "Canada Iqaluit, Nunavut", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444665248/ioy9ziiddmdz2xmrh2oh.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-13", "title": "HE NEVER DIED US Theatrical Release", "type": 1, "pledged": "795", "author": "Zach Hagen", "project_url": "https://www.indiegogo.com/projects/he-never-died-us-theatrical-release/pinw?sa=0&sp=0", "currency": "USD", "location": "Canada Toronto, Ontario", "category_id": "10", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444753523/hz56vrf9sk9dd1azyl14.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-13", "title": "Help End Viral Diseases with DRACOs", "type": 1, "pledged": "3841", "author": "Todd Rider", "project_url": "https://www.indiegogo.com/projects/help-end-viral-diseases-with-dracos/pinw?sa=0&sp=0", "currency": "USD", "location": "United States Acton, Massachusetts", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444751112/s9coq3xu6sdi5y1uxdcl.jpg", "id": "use title"}
