{"website": 2, "end": "2015-11-17", "title": "UTHERMIC Coldscreen Lotion", "type": 1, "pledged": "3584", "author": "U\u02daThermic", "project_url": "https://www.indiegogo.com/projects/uthermic-coldscreen-lotion/pinw?sa=0&sp=0", "currency": "USD", "location": "United States Boulder, Colorado", "category_id": "4", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444677499/uh49dqt8mjcepnmgnahv.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-28", "title": "KnotOut - Rollers Made to Fit Your Body!", "type": 1, "pledged": "6930", "author": "Sam Rainieri", "project_url": "https://www.indiegogo.com/projects/knotout-rollers-made-to-fit-your-body/pipp?sa=0&sp=0", "currency": "USD", "location": "United States Simi Valley, California", "category_id": "4", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444742995/urfpcefjuihfao7qh8ee.png", "id": "use title"}
{"website": 2, "end": "2015-12-13", "title": "Legal Fees", "type": 1, "pledged": "720", "author": "Eleni Vlachos", "project_url": "https://www.indiegogo.com/projects/legal-fees--30/pinw?sa=0&sp=0", "currency": "USD", "location": "United States Seattle, Washington", "category_id": "1", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444196412/uhf2tllgqhzymnpzjamp.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-12", "title": "Support for the amazing team of performers & DJs", "type": 1, "pledged": "0", "author": "Majestic Meadow-Gathering", "project_url": "https://www.indiegogo.com/projects/support-for-the-amazing-team-of-performers-djs/pinw?sa=0&sp=0", "currency": "USD", "location": "Canada Lawrence Lake, Alberta", "category_id": "3", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444677941/oir4fkdbzpssbfxzfpwm.png", "id": "use title"}
{"website": 2, "end": "2015-10-28", "title": "Secure the Longevity of Brooklyn Studios for Dance", "type": 1, "pledged": "8380", "author": "Pepper Fajans", "project_url": "https://www.indiegogo.com/projects/secure-the-longevity-of-brooklyn-studios-for-dance/pipp?sa=0&sp=0", "currency": "USD", "location": "United States Brooklyn, New York", "category_id": "4", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1440354430/clci6afpukhiuegpkssy.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-28", "title": "Zambra: Once-Forbidden Art in Danger of Extinction", "type": 1, "pledged": "965", "author": "Puela Lunaris", "project_url": "https://www.indiegogo.com/projects/zambra-once-forbidden-art-in-danger-of-extinction/pipp?sa=0&sp=0", "currency": "USD", "location": "United States New York - Granada, New York", "category_id": "1", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1440969080/ua9afu8yt5cni91uydsu.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-28", "title": "Zambra: Once-Forbidden Art in Danger of Extinction", "type": 1, "pledged": "965", "author": "Puela Lunaris", "project_url": "https://www.indiegogo.com/projects/zambra-once-forbidden-art-in-danger-of-extinction/pipp?sa=0&sp=0", "currency": "USD", "location": "United States New York - Granada, New York", "category_id": "3", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1440969080/ua9afu8yt5cni91uydsu.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-25", "title": "THE Seaweed Chocolate Bar", "type": 1, "pledged": "4760", "author": "Cole Meeker", "project_url": "https://www.indiegogo.com/projects/the-seaweed-chocolate-bar/pinw?sa=0&sp=0", "currency": "USD", "location": "United States Sonoma County, California", "category_id": "8", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1441261258/tkbek5dotybiu1zgvepc.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-13", "title": "The Muse Group: Inspired shopping", "type": 1, "pledged": "2614", "author": "Jessica Antista", "project_url": "https://www.indiegogo.com/projects/the-muse-group-inspired-shopping/pinw?sa=0&sp=0", "currency": "USD", "location": "Cote d'Ivoire Abidjan", "category_id": "5", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444249633/slxt802vp4wqtlcaamua.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-13", "title": "Good Girls", "type": 1, "pledged": "1260", "author": "Rose Georgiana", "project_url": "https://www.indiegogo.com/projects/good-girls/pinw?sa=0&sp=0", "currency": "AUD", "location": "Australia Gold Coast", "category_id": "10", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444584626/xfdzh8216v0xpvipyzod.png", "id": "use title"}
