{"website": 2, "end": "2015-12-12", "title": "Iqaluit Humane Society: Making Strides", "type": 1, "pledged": "1494", "author": "Heather Crowley", "project_url": "https://www.indiegogo.com/projects/iqaluit-humane-society-making-strides/pinw?sa=0&sp=0", "currency": "CAD", "location": "Canada Iqaluit, Nunavut", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444665248/ioy9ziiddmdz2xmrh2oh.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-07", "title": "AVIARY FOR RESCUED BIRDS", "type": 1, "pledged": "627", "author": "marcel.woolfe", "project_url": "https://www.indiegogo.com/projects/aviary-for-rescued-birds/pipp?sa=0&sp=0", "currency": "AUD", "location": "Australia Newcastle", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444282934/r33us0b7zc7r9ifr5m2y.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-12", "title": "Support for the amazing team of performers & DJs", "type": 1, "pledged": "0", "author": "Majestic Meadow-Gathering", "project_url": "https://www.indiegogo.com/projects/support-for-the-amazing-team-of-performers-djs/pinw?sa=0&sp=0", "currency": "USD", "location": "Canada Lawrence Lake, Alberta", "category_id": "3", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444677941/oir4fkdbzpssbfxzfpwm.png", "id": "use title"}
{"website": 2, "end": "2015-11-17", "title": "UTHERMIC Coldscreen Lotion", "type": 1, "pledged": "3584", "author": "U\u02daThermic", "project_url": "https://www.indiegogo.com/projects/uthermic-coldscreen-lotion/pinw?sa=0&sp=0", "currency": "USD", "location": "United States Boulder, Colorado", "category_id": "4", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444677499/uh49dqt8mjcepnmgnahv.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-12", "title": "National Museum of American Religion", "type": 1, "pledged": "2313", "author": "Colleen Prior", "project_url": "https://www.indiegogo.com/projects/national-museum-of-american-religion/pinw?sa=0&sp=0", "currency": "USD", "location": "United States Washington, District of Columbia", "category_id": "13", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444615576/vt5jpqmeouxh6zovyq4y.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-13", "title": "Sleepless in Seattle 2015 - Seattle Gives Back", "type": 1, "pledged": "8090", "author": "Eddie Wang", "project_url": "https://www.indiegogo.com/projects/sleepless-in-seattle-2015-seattle-gives-back--2/pinw?sa=0&sp=0", "currency": "USD", "location": "United States Seattle, Washington", "category_id": "14", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1443895682/fz7pu0sry0ur3rxucprs.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-12", "title": "Iqaluit Humane Society: Making Strides", "type": 1, "pledged": "1494", "author": "Heather Crowley", "project_url": "https://www.indiegogo.com/projects/iqaluit-humane-society-making-strides/pinw?sa=0&sp=0", "currency": "CAD", "location": "Canada Iqaluit, Nunavut", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444665248/ioy9ziiddmdz2xmrh2oh.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-12", "title": "Iqaluit Humane Society: Making Strides", "type": 1, "pledged": "1494", "author": "Heather Crowley", "project_url": "https://www.indiegogo.com/projects/iqaluit-humane-society-making-strides/pipp?sa=0&sp=0", "currency": "CAD", "location": "Canada Iqaluit, Nunavut", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444665248/ioy9ziiddmdz2xmrh2oh.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-07", "title": "AVIARY FOR RESCUED BIRDS", "type": 1, "pledged": "627", "author": "marcel.woolfe", "project_url": "https://www.indiegogo.com/projects/aviary-for-rescued-birds/pipp?sa=0&sp=0", "currency": "AUD", "location": "Australia Newcastle", "category_id": "3", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444282934/r33us0b7zc7r9ifr5m2y.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-07", "title": "AVIARY FOR RESCUED BIRDS", "type": 1, "pledged": "627", "author": "marcel.woolfe", "project_url": "https://www.indiegogo.com/projects/aviary-for-rescued-birds/pipp?sa=0&sp=0", "currency": "AUD", "location": "Australia Newcastle", "category_id": "4", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444282934/r33us0b7zc7r9ifr5m2y.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-07", "title": "AVIARY FOR RESCUED BIRDS", "type": 1, "pledged": "627", "author": "marcel.woolfe", "project_url": "https://www.indiegogo.com/projects/aviary-for-rescued-birds/pipp?sa=0&sp=0", "currency": "AUD", "location": "Australia Newcastle", "category_id": "13", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444282934/r33us0b7zc7r9ifr5m2y.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-07", "title": "AVIARY FOR RESCUED BIRDS", "type": 1, "pledged": "627", "author": "marcel.woolfe", "project_url": "https://www.indiegogo.com/projects/aviary-for-rescued-birds/pipp?sa=0&sp=0", "currency": "AUD", "location": "Australia Newcastle", "category_id": "14", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444282934/r33us0b7zc7r9ifr5m2y.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-07", "title": "AVIARY FOR RESCUED BIRDS", "type": 1, "pledged": "627", "author": "marcel.woolfe", "project_url": "https://www.indiegogo.com/projects/aviary-for-rescued-birds/pipp?sa=0&sp=0", "currency": "AUD", "location": "Australia Newcastle", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444282934/r33us0b7zc7r9ifr5m2y.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-13", "title": "Good Girls", "type": 1, "pledged": "1260", "author": "Rose Georgiana", "project_url": "https://www.indiegogo.com/projects/good-girls/pinw?sa=0&sp=0", "currency": "AUD", "location": "Australia Gold Coast", "category_id": "10", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444584626/xfdzh8216v0xpvipyzod.png", "id": "use title"}
{"website": 2, "end": "2015-11-25", "title": "THE Seaweed Chocolate Bar", "type": 1, "pledged": "4760", "author": "Cole Meeker", "project_url": "https://www.indiegogo.com/projects/the-seaweed-chocolate-bar/pinw?sa=0&sp=0", "currency": "USD", "location": "United States Sonoma County, California", "category_id": "8", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1441261258/tkbek5dotybiu1zgvepc.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-13", "title": "Legal Fees", "type": 1, "pledged": "720", "author": "Eleni Vlachos", "project_url": "https://www.indiegogo.com/projects/legal-fees--30/pinw?sa=0&sp=0", "currency": "USD", "location": "United States Seattle, Washington", "category_id": "1", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444196412/uhf2tllgqhzymnpzjamp.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-16", "title": "Sing the Sun's Return", "type": 1, "pledged": "265", "author": "Will Rowan", "project_url": "https://www.indiegogo.com/projects/sing-the-sun-s-return/pinw?sa=0&sp=0", "currency": "USD", "location": "United States Marlboro, Vermont", "category_id": "6", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444785570/ih20ix7bybg5qrgbxs8l.png", "id": "use title"}
{"website": 2, "end": "2015-12-13", "title": "Help End Viral Diseases with DRACOs", "type": 1, "pledged": "3841", "author": "Todd Rider", "project_url": "https://www.indiegogo.com/projects/help-end-viral-diseases-with-dracos/pinw?sa=0&sp=0", "currency": "USD", "location": "United States Acton, Massachusetts", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444751112/s9coq3xu6sdi5y1uxdcl.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-22", "title": "Dungeon Slayer - A Multi-Plattform Dungeon-Game", "type": 1, "pledged": "20", "author": "Oliver Collin", "project_url": "https://www.indiegogo.com/projects/dungeon-slayer-a-multi-plattform-dungeon-game/pinw?sa=0&sp=0", "currency": "EUR", "location": "Germany Brunnthal", "category_id": "7", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1443916111/oug3itpzplozrhxhcatc.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-13", "title": "The Muse Group: Inspired shopping", "type": 1, "pledged": "2614", "author": "Jessica Antista", "project_url": "https://www.indiegogo.com/projects/the-muse-group-inspired-shopping/pinw?sa=0&sp=0", "currency": "USD", "location": "Cote d'Ivoire Abidjan", "category_id": "5", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444249633/slxt802vp4wqtlcaamua.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-12", "title": "Sawyers - Preppy Bamboo Sunglasses", "type": 1, "pledged": "0", "author": "Wear Sawyer", "project_url": "https://www.indiegogo.com/projects/sawyers-preppy-bamboo-sunglasses/pipp?sa=0&sp=0", "currency": "USD", "location": "United States Naples, Florida", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444676914/fodx2cmg7mmkvb6oawcn.png", "id": "use title"}
{"website": 2, "end": "2015-11-10", "title": "IKURU- Empowering Women Through Colours", "type": 1, "pledged": "6115", "author": "Sarah Bove", "project_url": "https://www.indiegogo.com/projects/ikuru-empowering-women-through-colours/pipp?sa=0&sp=0", "currency": "USD", "location": "Mozambique Pemba", "category_id": "3", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1441977516/yri701ijxn5qll2fnm8r.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-10", "title": "IKURU- Empowering Women Through Colours", "type": 1, "pledged": "6115", "author": "Sarah Bove", "project_url": "https://www.indiegogo.com/projects/ikuru-empowering-women-through-colours/pipp?sa=0&sp=0", "currency": "USD", "location": "Mozambique Pemba", "category_id": "4", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1441977516/yri701ijxn5qll2fnm8r.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-10", "title": "IKURU- Empowering Women Through Colours", "type": 1, "pledged": "6115", "author": "Sarah Bove", "project_url": "https://www.indiegogo.com/projects/ikuru-empowering-women-through-colours/pipp?sa=0&sp=0", "currency": "USD", "location": "Mozambique Pemba", "category_id": "13", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1441977516/yri701ijxn5qll2fnm8r.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-10", "title": "IKURU- Empowering Women Through Colours", "type": 1, "pledged": "6115", "author": "Sarah Bove", "project_url": "https://www.indiegogo.com/projects/ikuru-empowering-women-through-colours/pipp?sa=0&sp=0", "currency": "USD", "location": "Mozambique Pemba", "category_id": "14", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1441977516/yri701ijxn5qll2fnm8r.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-10", "title": "IKURU- Empowering Women Through Colours", "type": 1, "pledged": "6115", "author": "Sarah Bove", "project_url": "https://www.indiegogo.com/projects/ikuru-empowering-women-through-colours/pipp?sa=0&sp=0", "currency": "USD", "location": "Mozambique Pemba", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1441977516/yri701ijxn5qll2fnm8r.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-13", "title": "The Muse Group: Inspired shopping", "type": 1, "pledged": "2614", "author": "Jessica Antista", "project_url": "https://www.indiegogo.com/projects/the-muse-group-inspired-shopping/pipp?sa=0&sp=0", "currency": "USD", "location": "Cote d'Ivoire Abidjan", "category_id": "10", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444249633/slxt802vp4wqtlcaamua.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-13", "title": "The Muse Group: Inspired shopping", "type": 1, "pledged": "2614", "author": "Jessica Antista", "project_url": "https://www.indiegogo.com/projects/the-muse-group-inspired-shopping/pipp?sa=0&sp=0", "currency": "USD", "location": "Cote d'Ivoire Abidjan", "category_id": "14", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444249633/slxt802vp4wqtlcaamua.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-13", "title": "The Muse Group: Inspired shopping", "type": 1, "pledged": "2614", "author": "Jessica Antista", "project_url": "https://www.indiegogo.com/projects/the-muse-group-inspired-shopping/pipp?sa=0&sp=0", "currency": "USD", "location": "Cote d'Ivoire Abidjan", "category_id": "8", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444249633/slxt802vp4wqtlcaamua.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-13", "title": "The Muse Group: Inspired shopping", "type": 1, "pledged": "2614", "author": "Jessica Antista", "project_url": "https://www.indiegogo.com/projects/the-muse-group-inspired-shopping/pipp?sa=0&sp=0", "currency": "USD", "location": "Cote d'Ivoire Abidjan", "category_id": "1", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444249633/slxt802vp4wqtlcaamua.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-13", "title": "The Muse Group: Inspired shopping", "type": 1, "pledged": "2614", "author": "Jessica Antista", "project_url": "https://www.indiegogo.com/projects/the-muse-group-inspired-shopping/pipp?sa=0&sp=0", "currency": "USD", "location": "Cote d'Ivoire Abidjan", "category_id": "6", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444249633/slxt802vp4wqtlcaamua.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-13", "title": "The Muse Group: Inspired shopping", "type": 1, "pledged": "2614", "author": "Jessica Antista", "project_url": "https://www.indiegogo.com/projects/the-muse-group-inspired-shopping/pipp?sa=0&sp=0", "currency": "USD", "location": "Cote d'Ivoire Abidjan", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444249633/slxt802vp4wqtlcaamua.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-13", "title": "The Muse Group: Inspired shopping", "type": 1, "pledged": "2614", "author": "Jessica Antista", "project_url": "https://www.indiegogo.com/projects/the-muse-group-inspired-shopping/pipp?sa=0&sp=0", "currency": "USD", "location": "Cote d'Ivoire Abidjan", "category_id": "7", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444249633/slxt802vp4wqtlcaamua.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-13", "title": "The Muse Group: Inspired shopping", "type": 1, "pledged": "2614", "author": "Jessica Antista", "project_url": "https://www.indiegogo.com/projects/the-muse-group-inspired-shopping/pipp?sa=0&sp=0", "currency": "USD", "location": "Cote d'Ivoire Abidjan", "category_id": "5", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444249633/slxt802vp4wqtlcaamua.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-09", "title": "Heat Presses To Decorate NYC Wear & Gear Goods", "type": 1, "pledged": "1425", "author": "Marcel Singleton", "project_url": "https://www.indiegogo.com/projects/heat-presses-to-decorate-nyc-wear-gear-goods/pipp?sa=0&sp=0", "currency": "USD", "location": "United States Cambridge, Massachusetts", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444189168/clmxkxbsqmakehqcynna.png", "id": "use title"}
{"website": 2, "end": "2015-11-10", "title": "Real Truth Church Purchase", "type": 1, "pledged": "36", "author": "Kenneth Mercury", "project_url": "https://www.indiegogo.com/projects/real-truth-church-purchase/pinw?sa=0&sp=0", "currency": "USD", "location": "United States Boston, Massachusetts", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1443624892/wbvaflv1t0qdrkeoxyrj.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-02", "title": "Send Female Driver Leona Chin to race in Japan", "type": 1, "pledged": "2159", "author": "Leona Lyweoi", "project_url": "https://www.indiegogo.com/projects/send-female-driver-leona-chin-to-race-in-japan/pinw?sa=0&sp=0", "currency": "USD", "location": "Malaysia Subang Jaya", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444695143/g1pqjqlpq6ibc85ibhe5.png", "id": "use title"}
{"website": 2, "end": "2015-11-13", "title": "NIGHT OF SCENES", "type": 1, "pledged": "190", "author": "Veronica St. Clair", "project_url": "https://www.indiegogo.com/projects/night-of-scenes/pinw?sa=0&sp=0", "currency": "USD", "location": "United States San Diego, California", "category_id": "12", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444768238/vcwiijxmvanxmnz0wbn0.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-12", "title": "How the BBC Stole the Referendum - The Documentary", "type": 1, "pledged": "1806", "author": "Alan Knight", "project_url": "https://www.indiegogo.com/projects/how-the-bbc-stole-the-referendum-the-documentary/pipp?sa=0&sp=0", "currency": "GBP", "location": "United Kingdom Edinburgh", "category_id": "3", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1443270931/rhidrtxuhoytowuxfnti.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-12", "title": "How the BBC Stole the Referendum - The Documentary", "type": 1, "pledged": "1806", "author": "Alan Knight", "project_url": "https://www.indiegogo.com/projects/how-the-bbc-stole-the-referendum-the-documentary/pipp?sa=0&sp=0", "currency": "GBP", "location": "United Kingdom Edinburgh", "category_id": "4", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1443270931/rhidrtxuhoytowuxfnti.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-12", "title": "How the BBC Stole the Referendum - The Documentary", "type": 1, "pledged": "1806", "author": "Alan Knight", "project_url": "https://www.indiegogo.com/projects/how-the-bbc-stole-the-referendum-the-documentary/pipp?sa=0&sp=0", "currency": "GBP", "location": "United Kingdom Edinburgh", "category_id": "13", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1443270931/rhidrtxuhoytowuxfnti.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-12", "title": "How the BBC Stole the Referendum - The Documentary", "type": 1, "pledged": "1806", "author": "Alan Knight", "project_url": "https://www.indiegogo.com/projects/how-the-bbc-stole-the-referendum-the-documentary/pipp?sa=0&sp=0", "currency": "GBP", "location": "United Kingdom Edinburgh", "category_id": "14", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1443270931/rhidrtxuhoytowuxfnti.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-12", "title": "How the BBC Stole the Referendum - The Documentary", "type": 1, "pledged": "1806", "author": "Alan Knight", "project_url": "https://www.indiegogo.com/projects/how-the-bbc-stole-the-referendum-the-documentary/pipp?sa=0&sp=0", "currency": "GBP", "location": "United Kingdom Edinburgh", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1443270931/rhidrtxuhoytowuxfnti.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-21", "title": "Shadow Play Series 2 - VENGEANCE", "type": 1, "pledged": "500", "author": "George Threadgold", "project_url": "https://www.indiegogo.com/projects/shadow-play-series-2-vengeance/pipp?sa=0&sp=0", "currency": "GBP", "location": "United Kingdom Welwyn Garden City", "category_id": "10", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1442866013/objpr6ijaecndob82l0n.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-21", "title": "Shadow Play Series 2 - VENGEANCE", "type": 1, "pledged": "500", "author": "George Threadgold", "project_url": "https://www.indiegogo.com/projects/shadow-play-series-2-vengeance/pipp?sa=0&sp=0", "currency": "GBP", "location": "United Kingdom Welwyn Garden City", "category_id": "14", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1442866013/objpr6ijaecndob82l0n.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-21", "title": "Shadow Play Series 2 - VENGEANCE", "type": 1, "pledged": "500", "author": "George Threadgold", "project_url": "https://www.indiegogo.com/projects/shadow-play-series-2-vengeance/pipp?sa=0&sp=0", "currency": "GBP", "location": "United Kingdom Welwyn Garden City", "category_id": "8", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1442866013/objpr6ijaecndob82l0n.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-21", "title": "Shadow Play Series 2 - VENGEANCE", "type": 1, "pledged": "500", "author": "George Threadgold", "project_url": "https://www.indiegogo.com/projects/shadow-play-series-2-vengeance/pipp?sa=0&sp=0", "currency": "GBP", "location": "United Kingdom Welwyn Garden City", "category_id": "1", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1442866013/objpr6ijaecndob82l0n.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-21", "title": "Shadow Play Series 2 - VENGEANCE", "type": 1, "pledged": "500", "author": "George Threadgold", "project_url": "https://www.indiegogo.com/projects/shadow-play-series-2-vengeance/pipp?sa=0&sp=0", "currency": "GBP", "location": "United Kingdom Welwyn Garden City", "category_id": "6", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1442866013/objpr6ijaecndob82l0n.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-21", "title": "Shadow Play Series 2 - VENGEANCE", "type": 1, "pledged": "500", "author": "George Threadgold", "project_url": "https://www.indiegogo.com/projects/shadow-play-series-2-vengeance/pipp?sa=0&sp=0", "currency": "GBP", "location": "United Kingdom Welwyn Garden City", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1442866013/objpr6ijaecndob82l0n.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-21", "title": "Shadow Play Series 2 - VENGEANCE", "type": 1, "pledged": "500", "author": "George Threadgold", "project_url": "https://www.indiegogo.com/projects/shadow-play-series-2-vengeance/pipp?sa=0&sp=0", "currency": "GBP", "location": "United Kingdom Welwyn Garden City", "category_id": "7", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1442866013/objpr6ijaecndob82l0n.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-21", "title": "Shadow Play Series 2 - VENGEANCE", "type": 1, "pledged": "500", "author": "George Threadgold", "project_url": "https://www.indiegogo.com/projects/shadow-play-series-2-vengeance/pipp?sa=0&sp=0", "currency": "GBP", "location": "United Kingdom Welwyn Garden City", "category_id": "5", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1442866013/objpr6ijaecndob82l0n.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-03", "title": "2 Girls 1 Show - From the Creators of Blogologues!", "type": 1, "pledged": "18041", "author": "Allison Goldberg & Jen Jamula", "project_url": "https://www.indiegogo.com/projects/2-girls-1-show-from-the-creators-of-blogologues/pipp?sa=0&sp=0", "currency": "USD", "location": "United States New York, New York", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1443628768/laps62sqvsj8zhe9ovme.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-18", "title": "Roomiess: Season 2", "type": 1, "pledged": "1487", "author": "Edward Kiniry-Ostro", "project_url": "https://www.indiegogo.com/projects/roomiess-season-2/pipp?sa=0&sp=0", "currency": "USD", "location": "United States Los Angeles, California", "category_id": "9", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444716525/pgl85ac4x89u0zkiwacq.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-18", "title": "Roomiess: Season 2", "type": 1, "pledged": "1487", "author": "Edward Kiniry-Ostro", "project_url": "https://www.indiegogo.com/projects/roomiess-season-2/pipp?sa=0&sp=0", "currency": "USD", "location": "United States Los Angeles, California", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444716525/pgl85ac4x89u0zkiwacq.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-18", "title": "Roomiess: Season 2", "type": 1, "pledged": "1487", "author": "Edward Kiniry-Ostro", "project_url": "https://www.indiegogo.com/projects/roomiess-season-2/pipp?sa=0&sp=0", "currency": "USD", "location": "United States Los Angeles, California", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444716525/pgl85ac4x89u0zkiwacq.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-18", "title": "Roomiess: Season 2", "type": 1, "pledged": "1487", "author": "Edward Kiniry-Ostro", "project_url": "https://www.indiegogo.com/projects/roomiess-season-2/pipp?sa=0&sp=0", "currency": "USD", "location": "United States Los Angeles, California", "category_id": "11", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444716525/pgl85ac4x89u0zkiwacq.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-18", "title": "Roomiess: Season 2", "type": 1, "pledged": "1487", "author": "Edward Kiniry-Ostro", "project_url": "https://www.indiegogo.com/projects/roomiess-season-2/pipp?sa=0&sp=0", "currency": "USD", "location": "United States Los Angeles, California", "category_id": "12", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444716525/pgl85ac4x89u0zkiwacq.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-11", "title": "Send Mo Mo to College of Wizardry", "type": 1, "pledged": "1628", "author": "Morgan O'Brien", "project_url": "https://www.indiegogo.com/projects/send-mo-mo-to-college-of-wizardry/pipp?sa=0&sp=0", "currency": "CAD", "location": "Canada Toronto, Ontario", "category_id": "3", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444570835/pu2wg5fw2koewwg7kosj.jpg", "id": "use title"}
