{"website": 2, "end": "2015-12-06", "title": "SAVE THE STRAYS IN BETHLEHEM!", "type": 1, "pledged": "457", "author": "Stela Moric", "project_url": "https://www.indiegogo.com/projects/save-the-strays-in-bethlehem/pinw?sa=0&sp=0", "currency": "USD", "location": "Bethlehem (all cities) Palestine, State of", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1445449579/unlhfpleqwwbqm1i09xv.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-06", "title": "SAVE THE STRAYS IN BETHLEHEM!", "type": 1, "pledged": "457", "author": "Stela Moric", "project_url": "https://www.indiegogo.com/projects/save-the-strays-in-bethlehem/pipp?sa=0&sp=0", "currency": "USD", "location": "Bethlehem (all cities) Palestine, State of", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1445449579/unlhfpleqwwbqm1i09xv.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-30", "title": "Wheelchair and harness for Ivy!", "type": 1, "pledged": "525", "author": "Isabel Galan Quiles", "project_url": "https://www.indiegogo.com/projects/wheelchair-and-harness-for-ivy/pipp?sa=0&sp=0", "currency": "GBP", "location": "London United Kingdom", "category_id": "15", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1445812028/f9vw3otmhqxkuainhtmh.png", "id": "use title"}
{"website": 2, "end": "2015-12-04", "title": "Eurydice Descended", "type": 1, "pledged": "775", "author": "Jessi Knight", "project_url": "https://www.indiegogo.com/projects/eurydice-descended/pinw?sa=0&sp=0", "currency": "USD", "location": "Durham, North Carolina United States", "category_id": "3", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1445909676/bhdqdw2xp6phe0ntdemb.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-30", "title": "The Dance Complex - Dance Building Building Dance", "type": 1, "pledged": "3182", "author": "Mary McCarthy", "project_url": "https://www.indiegogo.com/projects/the-dance-complex-dance-building-building-dance/pipp?sa=0&sp=0", "currency": "USD", "location": "Cambridge, Massachusetts United States", "category_id": "3", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1443144441/syyi7n0wbj7xhri882zh.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-27", "title": "JAYU: Sharing Human Rights Stories Through Art", "type": 1, "pledged": "2505", "author": "Gilad Cohen", "project_url": "https://www.indiegogo.com/projects/jayu-sharing-human-rights-stories-through-art/pinw?sa=0&sp=0", "currency": "CAD", "location": "Toronto, Ontario Canada", "category_id": "1", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1445714408/jfpiwnpd7sqcaelgcp9e.png", "id": "use title"}
{"website": 2, "end": "2015-11-28", "title": "Light My Fire! Wood-fired Kiln Rebuilding Project", "type": 1, "pledged": "360", "author": "David Voorhees", "project_url": "https://www.indiegogo.com/projects/light-my-fire-wood-fired-kiln-rebuilding-project/pipp?sa=0&sp=0", "currency": "USD", "location": "Zirconia, North Carolina United States", "category_id": "3", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1441223632/kfa8a0mxmnandbn2tcip.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-04", "title": "Art! Community! Joy! Give to The Secret City.", "type": 1, "pledged": "12728", "author": "Chris Wells", "project_url": "https://www.indiegogo.com/projects/art-community-joy-give-to-the-secret-city/pipp?sa=0&sp=0", "currency": "USD", "location": "New York, New York United States", "category_id": "1", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1441069992/zewpg8a4he6s42t34vey.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-30", "title": "Preserve Hornby's One-Room Schoolhouse Artifacts!", "type": 1, "pledged": "1125", "author": "Margaret Clark", "project_url": "https://www.indiegogo.com/projects/preserve-hornby-s-one-room-schoolhouse-artifacts/pinw?sa=0&sp=0", "currency": "USD", "location": "Erie, Pennsylvania United States", "category_id": "14", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1445623023/cg4hydlbsb1ukpwk1syj.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-28", "title": "The Perfect Sketchbook B5", "type": 1, "pledged": "11960", "author": "Erwin Lian", "project_url": "https://www.indiegogo.com/projects/the-perfect-sketchbook-b5/pinw?sa=0&sp=0", "currency": "USD", "location": "Singapore Singapore", "category_id": "4", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1445605778/q14woptfryb93kcs7xoa.jpg", "id": "use title"}
{"website": 2, "end": "2016-01-04", "title": "Luna: Bring the moon along with you", "type": 1, "pledged": "719729", "author": "Luna Moon", "project_url": "https://www.indiegogo.com/projects/luna-bring-the-moon-along-with-you/pipp?sa=0&sp=0", "currency": "USD", "location": "Taipei Taiwan", "category_id": "4", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1439974868/jvdxh1jvpwdyy2j1s73a.png", "id": "use title"}
{"website": 2, "end": "2015-12-04", "title": "World's Best TRAVEL JACKET with 15 Features-BauBax", "type": 1, "pledged": "10349025", "author": "yoganshi shah", "project_url": "https://www.indiegogo.com/projects/world-s-best-travel-jacket-with-15-features-baubax/pipp?sa=0&sp=0", "currency": "USD", "location": "Chicago, Illinois United States", "category_id": "4", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1441303606/i968pvd0sxli8byxkulx.png", "id": "use title"}
{"website": 2, "end": "2015-11-30", "title": "Armiriki Stories: From Crisis To Creation", "type": 1, "pledged": "1501", "author": "Christina & Konstantinos", "project_url": "https://www.indiegogo.com/projects/armiriki-stories-from-crisis-to-creation/pinw?sa=0&sp=0", "currency": "EUR", "location": "Athens Greece", "category_id": "5", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1445972286/kmvcw7kbipjhwmeptbpv.png", "id": "use title"}
{"website": 2, "end": "2015-12-13", "title": "Scrote'n'Tote: The Satchel of Life", "type": 1, "pledged": "281", "author": "Daniel Bitton", "project_url": "https://www.indiegogo.com/projects/scrote-n-tote-the-satchel-of-life/pipp?sa=0&sp=0", "currency": "USD", "location": "Montreal, Quebec Canada", "category_id": "5", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1446031736/ycv8tsiwabao65swqg8m.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-04", "title": "FOLLOW - Feature Film", "type": 1, "pledged": "7310", "author": "Brendan Merrill", "project_url": "https://www.indiegogo.com/projects/follow-feature-film/pinw?sa=0&sp=0", "currency": "USD", "location": "Los Angeles, California United States", "category_id": "10", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1446083981/ziqh5mburytjkhjx5xdf.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-30", "title": "Angels with Scaly Wings", "type": 1, "pledged": "2357", "author": "M. B. Saunders", "project_url": "https://www.indiegogo.com/projects/angels-with-scaly-wings/pinw?sa=0&sp=0", "currency": "EUR", "location": "Vienna Austria", "category_id": "7", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444931043/hd9hst5e2qa7znt3c1ua.png", "id": "use title"}
{"website": 2, "end": "2015-12-01", "title": "Cotton & Reed Distillery", "type": 1, "pledged": "34615", "author": "Reed Walker", "project_url": "https://www.indiegogo.com/projects/cotton-reed-distillery/pinw?sa=0&sp=0", "currency": "USD", "location": "Washington, District of Columbia United States", "category_id": "8", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1445928478/kzxrkwsnk3rc0ujpil78.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-04", "title": "Support Chappaqua Farmers Market Winter Market", "type": 1, "pledged": "920", "author": "Chappaqua Farmers Market Chappaqua", "project_url": "https://www.indiegogo.com/projects/support-chappaqua-farmers-market-winter-market/pipp?sa=0&sp=0", "currency": "USD", "location": "Chappaqua, New York United States", "category_id": "7", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1442602784/und8l62z8clubhkekscf.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-06", "title": "My dream", "type": 1, "pledged": "710", "author": "ILYES SOLTANI", "project_url": "https://www.indiegogo.com/projects/my-dream--724/pinw?sa=0&sp=0", "currency": "USD", "location": "Brooklyn, New York United States", "category_id": "9", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1446059180/lutis09bjbi1l4tnskzf.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-26", "title": "working title- Max: Collective", "type": 1, "pledged": "1279", "author": "Max Malanaphy", "project_url": "https://www.indiegogo.com/projects/working-title-max-collective/pinw?sa=0&sp=0", "currency": "USD", "location": "Minneapolis, Minnesota United States", "category_id": "12", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444588577/ilpmzn5yqkvtjf31ry37.jpg", "id": "use title"}
{"website": 2, "end": "2015-12-06", "title": "BELOVED PREY: The Traveling Opera", "type": 1, "pledged": "8352", "author": "Kento Iwasaki", "project_url": "https://www.indiegogo.com/projects/beloved-prey-the-traveling-opera/pipp?sa=0&sp=0", "currency": "USD", "location": "New York, New York United States", "category_id": "12", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1440704316/svzbdqwilh2aznipovbx.png", "id": "use title"}
{"website": 2, "end": "2015-11-30", "title": "Agnes of God", "type": 1, "pledged": "495", "author": "Agnes of God", "project_url": "https://www.indiegogo.com/projects/agnes-of-god--2/pipp?sa=0&sp=0", "currency": "CAD", "location": "Montreal, Quebec Canada", "category_id": "12", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1445558269/qaporgha0ex9d9yip7vx.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-26", "title": "working title- Max: Collective", "type": 1, "pledged": "1279", "author": "Max Malanaphy", "project_url": "https://www.indiegogo.com/projects/working-title-max-collective/pipp?sa=0&sp=0", "currency": "USD", "location": "Minneapolis, Minnesota United States", "category_id": "12", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444588577/ilpmzn5yqkvtjf31ry37.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-30", "title": "Help Annie Stay in University!", "type": 1, "pledged": "2590", "author": "Eleanor Kate", "project_url": "https://www.indiegogo.com/projects/help-annie-stay-in-university/pinw?sa=0&sp=0", "currency": "GBP", "location": "London United Kingdom", "category_id": "13", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1445972192/z4jk5izabiqmqppv0gvn.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-30", "title": "Dev4X Moonshot Education Project", "type": 1, "pledged": "1260", "author": "Bodo Hoenen", "project_url": "https://www.indiegogo.com/projects/dev4x-moonshot-education-project/pipp?sa=0&sp=0", "currency": "USD", "location": "New York, New York United States", "category_id": "13", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1446085383/wb0mpctchjruussicszs.png", "id": "use title"}
{"website": 2, "end": "2015-12-04", "title": "Pandemonium in Paris", "type": 1, "pledged": "4308", "author": "Robin Knox", "project_url": "https://www.indiegogo.com/projects/pandemonium-in-paris/pinw?sa=0&sp=0", "currency": "USD", "location": "Arlington Heights, Illinois United States", "category_id": "14", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1445977489/byepbvquho3rbbpghano.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-30", "title": "Pandemonium in Paris", "type": 1, "pledged": "4308", "author": "Robin Knox", "project_url": "https://www.indiegogo.com/projects/pandemonium-in-paris/pipp?sa=0&sp=0", "currency": "USD", "location": "Arlington Heights, Illinois United States", "category_id": "14", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1445977489/byepbvquho3rbbpghano.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-30", "title": "Kea Kites: Make your own kite & help save the Kea!", "type": 1, "pledged": "1402", "author": "Tamsin Orr-Walker", "project_url": "https://www.indiegogo.com/projects/kea-kites-make-your-own-kite-help-save-the-kea/pipp?sa=0&sp=0", "currency": "USD", "location": "Nelson New Zealand", "category_id": "14", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1445645058/l8iybcerhhxiivcynrzd.png", "id": "use title"}
{"website": 2, "end": "2015-11-30", "title": "The Very Scary Time Trial", "type": 1, "pledged": "1165", "author": "Ashley Carelock", "project_url": "https://www.indiegogo.com/projects/the-very-scary-time-trial/pipp?sa=0&sp=0", "currency": "USD", "location": "Cortez, Colorado United States", "category_id": "14", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444753512/sxqeqcvgge50vh96drzt.jpg", "id": "use title"}
{"website": 2, "end": "2015-11-30", "title": "The Sy & Marissa Show - Sketch Comedy Web Series", "type": 1, "pledged": "755", "author": "Marissa Madsen", "project_url": "https://www.indiegogo.com/projects/the-sy-marissa-show-sketch-comedy-web-series/pipp?sa=0&sp=0", "currency": "USD", "location": "Los Angeles, California United States", "category_id": "14", "img_url": "https://c1.iggcdn.com/indiegogo-media-prod-cld/image/upload/c_fill,f_auto,h_220,w_220/v1444935155/vhaqavetiur7ow3s3hta.jpg", "id": "use title"}
